### ISSUE TITLE
Query Composer not working, showing "No Schema Available" after update to 1.27.0

### ISSUE THREAD

**Issue by leannechen** [wp-graphql/wp-graphql#3171] opened 2024-07-09 09:00 UTC
### Description

The Query Composer is showing blank content after upgrading to 1.27.0, and same in 1.27.2.
It used to work before the update, but now showing "No Schema Available" screen, make it hard to inspect available schema.

![blank-screen](https://github.com/wp-graphql/wp-graphql/assets/35912430/c8621044-bb81-43f6-9fdf-512ab52bf5c7)

### Steps to reproduce

1. Go to GraphiQL IDE
2. Click "Query Composer" button on top of IDE
3. See the Query Composer panel

- Expected result: Seeing available schemas in GraphQL
- Actual result: "No Schema Available"

### WPGraphQL Version

1.27.2

### WordPress Version

6.5.5

### PHP Version

7.4.33

### Additional environment details

React + Next.js project

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by josephfusco** [comment] 2024-07-09 15:10
Hey @leannechen, I would recommend checking out [WPGraphQL's debugging docs](https://www.wpgraphql.com/docs/debugging), specifically the section [checking the response](https://www.wpgraphql.com/docs/debugging#checking-the-response), which shows how use your browser developer tools in order to help troubleshoot.

I would also recommend testing your setup with all plugins deactivated except for WPGraphQL. If the issue no longer exists, you can activate the plugins one-by-one in order to identify the problematic plugin.

**Comment by jasonbahl** [comment] 2024-07-11 14:37
@leannechen wanted to check in and see if you were able to get more information after following the debugging docs in the link @josephfusco provided.

Typically in your browser's developer tools you can inspect the response and _usually_ get more information. Enabling GraphQL Debug mode from the GraphQL > Settings page also helps with getting more clarity on errors.

The more information you can gather about _why_ the Schema is not available, the more we might be able to help.

**Comment by robbiebel** [comment] 2024-07-14 21:12
There was no errors on network response for me, but in debug.log I was getting Allocated Memory error and I fixed it by making unlimited it.

@jasonbahl thank you for this amazing plugin. I wanted to ask in here instead creating new issue.

I'm getting ERROR FETCHING SCHEMA in WPGraphQL IDE when I click "< Docs". But in Query Composer everything works well.

Also I get some interface type errors even I don't run query. The errors relational with another plugins such as https://github.com/AxeWP/wp-graphql-rank-math, WooGraphQL plugins. I searched for their repo issues and changelogs but i did find nothing.

I think somehow the schema should needs regenerated as blind predict. And first sight ideas for this?

And sometimes I need change some mutations and register them from scratch for example adding reCaptcha or something different. And I cant deregister the original mutateAndPayload and getting like

> `"type": "DUPLICATE_FIELD",
        "message": "You cannot register duplicate fields on the same Type. The field 'login' already exists on the type 'RootMutation'. Make sure to give the field a unique name.",
        "field_name": "login",
        "type_name": "RootMutation",`

if you have any advice for it i would be grateful.

Thank you

**Comment by justlevine** [comment] 2024-07-14 21:40
>There was no errors on network response for me,[...] I'm getting ERROR FETCHING SCHEMA in WPGraphQL IDE when I click "< Docs". But in Query Composer everything works well.

Clicking docs should have generated a failed XHR request to the `?graphql` endpoint which should have in addition to the request trigged on load that is responsible for the `No Schema Available` message. Please make sure you have the network tab open before you refresh the page, and click the checkbox in the tab to disable caching.

> Also I get some interface type errors even I don't run query. The errors relational with another plugins such as https://github.com/AxeWP/wp-graphql-rank-math, WooGraphQL plugins. I searched for their repo issues and changelogs but i did find nothing.

Ref: https://github.com/AxeWP/wp-graphql-rank-math/issues/99 

Please confirm that with all other plugins disabled, WPGraphQL itself works as expected, if so we can close this ticket out to free up our core maintainers while I'll follow up with you in the above issue directly.

> 
> I think somehow the schema should needs regenerated as blind predict. And first sight ideas for this?

The schema is generated on every load. So long as you're refreshing the page, this is not a "stale" schema but something active (plugins /custom code) that's breaking.


> And sometimes I need change some mutations and register them from scratch for example adding reCaptcha or something different. And I cant deregister the original mutateAndPayload and getting like
> 
> > `"type": "DUPLICATE_FIELD",         "message": "You cannot register duplicate fields on the same Type. The field 'login' already exists on the type 'RootMutation'. Make sure to give the field a unique name.",         "field_name": "login",         "type_name": "RootMutation",`
> 

Okay, so now there's _also_ custom code in the mix (and seeming preexisting `login` mutation from another unmentioned plugin that's conflicting with the custom code).
- If you disable/comment your code out does GraphiQL start working again?
- Are you using one of the `deregister_graphql_*()` to remove the old item from the schema before adding your custom ones?


As a general reminder, this is a bug tracker (community support happens over on Discord). If the issue isn't related to a specific plugin and the other above tips don't get you sorted, please respond with a minimally viable reproduction so we can continue to help you sort this out. If we can't replicate the bug there's not much we can do to solve it sadly.

**Comment by robbiebel** [comment] 2024-07-15 11:43
If you disable/comment your code out does GraphiQL start working again?
The custom code works already, but yes If i remove it the debug is clean.
Are you using one of the deregister_graphql_*() to remove the old item from the schema before adding your custom ones?
Yes I tried with deregister_grapql_mutation. I think that my code works before original mutation and the duplicate error comes after second run with original class function. I have searched but I dind't see any filter for mutations to make on that behavior.

**Comment by leannechen** [comment] 2024-08-12 02:36
Hi @josephfusco and @jasonbahl,

I've checked the debugging docs and checking the response, no errors found.
However, it turns out to be functioning when I disabled all the other plugins. So I think it is one of my plugins conflicting with WPGraphQL, just that I haven't got time to try one by one to know the exact one. Will report here if further discoveries.

Thank you for the reply and waiting!


As to the issue reported by @robbiebel, I am not encountering and not sure if it's the same issue with mine or not, therefore unable to give any feedback.

**Comment by josephfusco** [comment] 2024-08-12 15:10
Hey @leannechen, we are going to close this issue.

If you are able to identify a conflict with another plugin and believe there is a bug with WPGraphQL, please open a new issue with clear steps to reproduce and we will check it out! Thanks! 🙌🏼

**Closed by josephfusco** 2024-08-12 15:10 UTC
Labels: Invalid?, Status: Awaiting Author Response

**Comment by cavemon** [comment] 2024-08-15 17:47
Had a similar issue and it turns out I had given a custom field a `graphql_single_name` of `Category` which is creates a conflict for obvious reasons in WP.

**Comment by leannechen** [comment] 2024-09-06 07:32
I discovered that my issue was actually caused by the [Events Manager](https://wordpress.org/plugins/events-manager/) plugin (v5.12). 
The WP GraphQL Query Composer works correctly once the Events Manager plugin is deactivated.
