### ISSUE TITLE
Error when running gatsby build without clearing cache - not finding graphql values in gatsby-node.js

### ISSUE THREAD

**Issue by mikexavier** [wp-graphql/wp-graphql#1667] opened 2021-01-07 17:19 UTC
Hey, I’m running into an issue when using **gatsby build** (local and remote)

```
ERROR #11321  PLUGIN
"gatsby-node.js" threw an error while running the createPages lifecycle:
Cannot read property 'adventureParkGlobal' of null
  210 |   const contentNodes = result.data.allWpContentNode.nodes
  211 |   const wp = result.data.wp
> 212 |   const wpOptions = wp.adventureParkGlobal.globalData
      |                        ^
  213 | 
```

If I clear the cache then build, it builds with no issue every time.

I had a look [here](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/debugging-and-troubleshooting.md#node-sourcing-graphql-errors) but not really sure it’s relevant to what’s going on here?

Any ideas as to the reasons something like this might happen?

I wish I could tell you what I did before this started happening, but I feel like I only updated the code on the contact page

I'm using
- gatsby-source-wordpress-experimental 6.0.0
- WP GraphQL 1.0.5
- WP Gatsby 0.9.1

**Comment by jasonbahl** [comment] 2021-01-08 03:06
> If I clear the cache then build, it builds with no issue every time.

This leads me to believe the issue is not a WPGraphQL issue, but either a Gatsby Source WordPress issue or a Gatsby Core issue. 

I believe you're experiencing the same thing as the folks in this issue: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/386

If so, I'd recommend adding any helpful details to that issue. If you believe it's a different situation than described in that issue, open a new one on the source plugin so we can track it there. 

The more info you can provide, the better. Ideally, a Gatsby repo that we can look at the code for and reproduce would help. 

Going to close this issue on this repo in favor of #386 (or a new issue on that repo if you feel it's necessary)

**Closed by jasonbahl** 2021-01-08 03:06 UTC
