### ISSUE TITLE
ERROR #gatsby-source-wordpress_111002 after upgrading to 1.11.0

### ISSUE THREAD

**Issue by Haldaug** [wp-graphql/wp-graphql#2548] opened 2022-09-27 11:57 UTC
### Description

After upgrading from 1.10.0 to 1.11.0 (and 1.11.1) gatsby-source-wordpress fails to fetch the categories.

### Steps to reproduce

I use WPGraphQL in conjuction with Gatsby to be able to use Wordpress as a headless CMS. After upgrading WPGraphQL from 1.10.0 to 1.11.0 i get the following error from gatsby-source-wordpress, failing the build:

```
ERROR #gatsby-source-wordpress_111002 

 gatsby-source-wordpress  Error: Parse Error: Header overflow
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)

Error occurred while fetching nodes of the "Category" type.
```

Reverting WPGraphQL back to 1.10.0 fixes the problem.

### WPGraphQL Version

1.11.0

### WordPress Version

6.0.2

### PHP Version

8.0.23

### Additional enviornment details

WP Gatsby 2.3.3
Gatsby 4.23.1
gatsby-source-wordpress 6.23.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by nminchow** [comment] 2022-09-27 22:31
Looks like a duplicate of https://github.com/wp-graphql/wp-graphql/issues/2548

**Comment by justlevine** [comment] 2022-09-27 23:06
@nminchow good catch!

The workaround right now is to disable the query analyzer programmatically with:
```php 
add_action( 'graphql_should_analyze_queries', '__return_false' );
```

I think there's a bigger 'issue' at play that we need to resolve, which is different than the referenced issue (about exposing this as a Settings toggle). since in an ideal world `gatsby-source-wordpress` would _just work_ - be it by optimizing the payload size created by the query analyzer, or disabled as incompatible automatically by WPGatsby.

**Comment by Haldaug** [comment] 2022-09-28 06:56
The workaround fixed my problem. Thank you!

**Comment by jasonbahl** [comment] 2022-09-28 20:59
Closing as a duplicate of #2535. 

PR coming that chunks the headers so default behavior shouldn't break for clients with an 8k limit. 🙏🏻

**Closed by jasonbahl** 2022-09-28 20:59 UTC
Labels: type: bug, Component: Query, Gatsby, has: workaround
