### ISSUE TITLE
Failed to open stream: No such file or directory plugins/wp-graphql/build

### ISSUE THREAD

**Issue by drozzi-pro** [wp-graphql/wp-graphql#2306] opened 2022-03-23 15:09 UTC
When installing the plugin via composer.
I get an error: `plugins/wp-graphql/build/index.asset.php - failed to open stream: No such file or directory`

I noticed that there is no build folder in the plugin folder at all
I went to the plugin folder executed

the `npm i` and `npm run build` commands and the problem went away, but I want to inform you that there is no build folder in the code that installs composer

The GraphQL IDE interface has appeared, but I have an endless loading
Error js: Uncaught (in promise) GraphQLError: Names must only contain [_a-zA-Z0-9] but "Template_Пустой" does not.

As a result, I had to download the plugin as a separate archive and install it without composer

Pure wordpress version 5.9.2
GraphQL Version 1.7.2

**Comment by justlevine** [comment] 2022-03-23 18:22
Hey @drozzi-pro ,

Any chance you downloaded the _branch_ directly from GitHub? (vs as a composer dep, downloading the release, or downloading/installing from wordpress.org?) 
If so, I believe that's intentional behavior.

**Comment by justlevine** [comment] 2022-03-23 18:24
Duplicate of #2282

**Closed by justlevine** 2022-03-23 18:24 UTC
Labels: Duplicate
