### ISSUE TITLE
Fatal error in 1.6.1

### ISSUE THREAD

**Issue by hatsumatsu** [wp-graphql/wp-graphql#2047] opened 2021-08-01 13:26 UTC
After updating from wp-graphql 1.5.8. to 1.6.1 my nextjs's queries result in a fatal error with the following stack trace. Downgrading to 1.5.8 fixes the issue.

**Update:** the same error occurs when querying the schema in the wp-graphql IDE.

wp-graphql 1.6.1
wp-graphql-jwt-authentication 0.4.0
wp-graphql-acf 0.4.0

`````
PHP Fatal error:  Uncaught ArgumentCountError: header() expects at least 1 parameter, 0 given in /***/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php:406
Stack trace:
#0 /***/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php(406): header()
#1 /***/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Definition/FieldDefinition.php(208): GraphQL\Type\Schema::resolveType('Header')
#2 /***/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php(287): GraphQL\Type\Definition\FieldDefinition->getType()
#3 /***/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Language/Visitor.php(466): GraphQL\Utils\TypeInfo->enter(Object(GraphQL\Language\AST\FieldNode))
#4 /***/wp-content/plugins/wp in /***/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php on line 406
`````

**Comment by tradaonline** [comment] 2021-08-02 05:56
I have this problem too.

**Comment by jasonbahl** [comment] 2021-08-02 15:52
@hatsumatsu Thank you for opening this issue and sharing the plugin versions you have active. 

Can you share your ACF Field Group export as JSON so I can try and reproduce?

Thanks 🙏🏻

**Comment by hatsumatsu** [comment] 2021-08-02 16:11
@jasonbahl thanks for getting back. It's happening in a production project with > 30 field groups but happy to share the data. what's the best way to share this non-publicly?

**Comment by jasonbahl** [comment] 2021-08-02 16:17
@hatsumatsu if you join the WPGraphQL Slack ([join here](Join the WPGraphQL community on Slack)), you can DM it to me.

**Comment by jasonbahl** [comment] 2021-08-02 16:40
Using the Field Group Export provided here: https://github.com/wp-graphql/wp-graphql-acf/blob/develop/docs/field-group-examples-export.json

I'm able to use GraphiQL in the admin of the IDE and in my query you can see the following plugins: 

- ACF PRO v5.9.8
- WPGraphQL v1.6.1
- WPGraphQL for ACF v0.4.0
- WPGraphQL JWT Auth v0.4.1

![Screen Shot 2021-08-02 at 10 36 14 AM](https://user-images.githubusercontent.com/1260765/127894785-6e0f2672-83b1-4201-b790-61a54e354643.png)

---- 

@hatsumatsu in addition to sharing the export with me in Slack, could you maybe try de-activating some extensions, like WPGraphQL for ACF, one at a time, and see if GraphiQL comes back? See if we can narrow down the conflicting plugin? 

Right now, my hunch is that possibly a specific ACF Field Group configuration is causing the issue, but It's hard to say for sure.

**Comment by jasonbahl** [comment] 2021-08-02 16:45
@hatsumatsu I'm seeing in your error the issue is happening with the type `Header`. 

Do you know where the `Header` Type is defined? Is it an ACF Field Group? Or something else?

Understanding how that Type is registered to ACF might help me understand how this bug is happening.

**Comment by hatsumatsu** [comment] 2021-08-02 16:51
@jasonbahl Deactivating wp-graphql-acf fixes the error so it looks it has something to do with the way my fields are configured. 

`header` (lowercase) is an ACF option page with a bunch of fields. The option page is configured like

`````
        acf_add_options_sub_page(
            array(
                'menu_slug' => 'header',
                'page_title' => __( 'Header', 'cxs' ),
                'parent_slug' => 'modules',
                'show_in_graphql' => true,
            )
        );  
````

**Comment by jasonbahl** [comment] 2021-08-02 17:00
@hatsumatsu I imported your Field Group that you shared in Slack and did not have any issues.

However, once I added the code above to add the options page, I also no longer can load GraphiQL. 

Bad news that we have a bug, but good news that I can reproduce! Now I can work toward a proper fix!

**Comment by jasonbahl** [comment] 2021-08-02 17:01
I didn't mean to close this, so I re-opened.

**Comment by jasonbahl** [comment] 2021-08-02 22:13
@hatsumatsu ah! This one is going to be interersting. 

I believe the conflict is with Type names added to the GraphQL Schema that have the same name as a PHP function. 

For example, the Type `header` is trying to call `header()` which is a PHP function (https://www.php.net/manual/en/function.header.php). 

This does seem like a regression caused by WPGraphQL 1.6 lazy loading of Types. 

I'm looking into bugfixes for this, but one thing you can do right now to fix this on your end is to add `graphql_field_name` to your submenu page and name it something unique like `headerSettings`: 

```php
acf_add_options_sub_page(
	array(
		'menu_slug' => 'header',
		'page_title' => __( 'Header', 'myDomain' ),
		'parent_slug' => 'modules',
		'show_in_graphql' => true,
		'graphql_field_name' => 'headerSettings',
	)
);
```

I'm looking into ways we can avoid this conflict. 

One thought I have (just brain dumping) is that when Types are added to the TypeRegistry, we can prefix them as `graphql_type_${name}` so that instead of a Type `Header` calling `header()` it would call `graphql_type_header()` 

I'm working through this, but I think I have a good idea how we can solve this while still respecting the benefits of the new Lazy Loading types.

**Comment by jasonbahl** [comment] 2021-08-03 15:32
@hatsumatsu I have a PR to WPGraphQL that fixes this. 

I was able to use your ACF Field Group as well as your ACF Option Page registration to query ACF fields with the changes in this PR in place: https://github.com/wp-graphql/wp-graphql/pull/2051

**Closed** 2021-08-04 16:57 UTC
Labels: ACF, Bug, Needs to be reproduced, Regression

**Comment by jasonbahl** [comment] 2021-08-04 17:23
@hatsumatsu v1.6.2 has been released. 

If you're still having issues after updating to 1.6.2, open a new issue with steps to reproduce and you can even mention this issue for reference, but I believe we resolved at least the original issue we were tracking with the `Header` type causing issues.

**Comment by hatsumatsu** [comment] 2021-08-04 18:00
@jasonbahl 1.6.2 fixes the bug in my environment. Thanks for the amazing support!

**Comment by jasonbahl** [comment] 2021-08-04 18:34
@hatsumatsu sweet! Thanks for the follow-up confirming this is resolved 🙏🏻
