### ISSUE TITLE
Getting menu with children returns an error 502

### ISSUE THREAD

**Issue by ChamperNet** [wp-graphql/wp-graphql#2531] opened 2022-09-21 16:59 UTC
### Description

Getting the main menu without children attached to it works fine. But if it has them, it returns an error.

### Steps to reproduce

Query: 

query GetMainMenu($id: ID = "someMenusId") {
  menu(id: $id) {
    menuItems(first: 30, after: null) {
      nodes {
        id
        label
        path
        parentId
        childItems {
          nodes {
            id
            label
            path
            parentId
          }
        }
      }
    }
  }
}
work fine for me if the menu's first level items haven't any children

But in over way it returns that error (no matter what the elements name or URI is):
{
  "errors": {
    "message": "Unexpected token '<', \"<html>\r\n<h\"... is not valid JSON",
    "stack": "SyntaxError: Unexpected token '<', \"<html>\r\n<h\"... is not valid JSON"
  }
}

The HTML answer is just a 502 bad gateway error.

### Additional context

I don't know: maybe this error is not connected with the hierarchy of the menu but with its item count.
But just one another item (more than 9) - and it throws me that error.

### WPGraphQL Version

v1.11.0

### WordPress Version

6.0

### PHP Version

8.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment] 2022-09-21 19:32
closing as a duplicate of #2530 

PR open already #2532

**Closed by jasonbahl** 2022-09-21 19:32 UTC

**Comment by jasonbahl** [comment] 2022-09-21 20:46
@ChamperNet release v1.11.1 has been published with the fix for this.

**Comment by ChamperNet** [comment] 2022-09-22 10:16
> @ChamperNet release v1.11.1 has been published with the fix for this.

Thank you a lot!
