### ISSUE TITLE
Issue to fetch more childItems on query

### ISSUE THREAD

**Issue by LinkGraph2021** [wp-graphql/wp-graphql#2928] opened 2023-09-08 21:40 UTC
### Description

I want to fetch more than 10 items on childItems on query, but doesn't work on my end

### Steps to reproduce

/* file: front-page.js */
footerMenuItems: menuItems(where: { location: $footerLocation, parentDatabaseId: 0 }) {
      nodes {
        ...NavigationMenuItemFragment
      }
}

/* file: MenuItems.js */
import { useState } from 'react';
import { gql } from '@apollo/client';

export default function MenuItems({ 
    items,
    keyI,
    classMenu,
    classAParent,
    classAChild
}) {
    console.log( items );
    return(
        <ul className={`${classMenu}`}>
            {items.map((linkM, index) => {
                return(
                    <li key={`${linkM.label}-list${keyI}`} className={`${classAParent} menu-items`}>
                        <a href={linkM.url} className={`menu-link`} dangerouslySetInnerHTML={{__html: linkM.label}}></a>
                        {linkM.childItems.nodes.length > 0 &&
                            <ul className="sub-menu">
                                {linkM.childItems.nodes.map((submenu, index) => (
                                    <li key={`${submenu.label}-childlist${keyI}`} className={`${classAChild} submenu-items`}>
                                        <a className={`submenu-link`} href={submenu.url} dangerouslySetInnerHTML={{__html: submenu.label}}></a>
                                    </li>
                                ))}
                            </ul>
                        }
                    </li>
                )
            })}
        </ul>
    );
}

MenuItems.fragments = {
  entry: gql`
    fragment NavigationMenuItemFragment on MenuItem {
        id
        label
        path
        title
        cssClasses
        parentId
        menuFields {
            isReversed
            newIcon {
                altText
                mediaItemUrl
            }
            haveTitle
        }
        childItems(first: 50) {
            nodes {
                label
                path
                title
                cssClasses
                url
                menuFields {
                    isReversed
                    newIcon {
                        altText
                        mediaItemUrl
                    }
                    haveTitle
                }
            }
        }
    }
  `,
};

### Additional context

The issue on the above thing is that on childItems on 'MenuItems.js' query can't get the first:50 instead of default that is 10

### WPGraphQL Version

1.8.2

### WordPress Version

6.3

### PHP Version

8.0.30

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment] 2023-09-08 21:52
Hey @LinkGraph2021 

I see you're using a (very) old version of WPGraphQL. Can you test against the latest v1.16.0, and confirm the issue is still happening?

(Ideally, run the query in the WPGraphiQL IDE on the backend and share a screenshot of the results, to confirm the issue is related to WPGraphQL and not an issue with your frontend configuration.)

Thanks!

**Comment by justlevine** [comment] 2023-09-30 16:50
Hey @LinkGraph2021, since we havn't heard back from you, I'm going to assume the issue was resolved by updating WPGraphQL to v1.16.0 (latest version as of writing).

For reference, here is a query returning more than 10 `childItems`.
![image](https://github.com/wp-graphql/wp-graphql/assets/29322304/ac108f90-0296-439f-bdf0-94a1bd54ccd6)

If you're still running into this issue in the latest version, please open up a new issue with a replicable test case and we'll be happy to investigate.

**Closed by justlevine** 2023-09-30 16:50 UTC
Labels: type: bug, needs: reproduction, status: awaiting author response, Component: Connections, ObjectType: Menu
