### ISSUE TITLE
When using non-ascii characters, generated an invalid schema.

### ISSUE THREAD

**Issue by mecaota** [wp-graphql/wp-graphql#2807] opened 2023-05-08 09:37 UTC
### Description

Here, it is assumed that there is a template file with meta information set for the following.

```php
<?php
/*
Template Name: 会社概要ページ トップ
*/

/* some contents is returned */

```

In this case, generated schema file's `ContentTemplate` node is here.

```grahql
"""The template assigned to the node"""
type Template_会社概要ページトップ implements ContentTemplate {
  """The name of the template"""
  templateName: String
}
```

This is invalid schema, because schema type is accepted only ascii characters. So GraphQL IDE show error message in browser console as below.

```
Uncaught (in promise) GraphQLError: Names must only contain [_a-zA-Z0-9] but "Template_会社概要ページトップ" does not.
```

### Steps to reproduce

1. Create a template file and set the template name to non-ASCII characters(ex: jp, zh-CN, ar).
```php
<?php
/*
Template Name: 会社概要ページ トップ
*/

/* some contents is returned */

```

2. Run wordpress with the aforementioned template

```graphql
query Reproduction {
  post(id: "0") {
    template {
      ... on Template_会社概要ページトップ {
        templateName
      }
    }
  }
}
```

#### Related code

https://github.com/wp-graphql/wp-graphql/blob/e37f2e06ded15647630a71c830d35c3f46f1d2b7/src/Type/InterfaceType/ContentTemplate.php#L39-L47

This code use `Template Name`. If use file name without extension, it will be repaired. But if file name was used non-ascii characters, there's nothing we can do about it 😇 

However, almost non-ascii character country(at least in japan), programmatic code's file name is usually used ascii characters.

#### Related issue

- https://github.com/wp-graphql/wp-graphql/issues/1658

### WPGraphQL Version

1.14.3

### WordPress Version

6.2

### PHP Version

8.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by mecaota** [comment] 2023-05-08 11:59
https://github.com/wp-graphql/wp-graphql/blob/e37f2e06ded15647630a71c830d35c3f46f1d2b7/src/Type/InterfaceType/ContentTemplate.php#L52C30-L56

`empty('')` will be return false. We should replace 'empty' to 'is_null', but this make blank template type name is generated.

After all, I feel that there is no choice but to use the file name to prevent it.


Maybe [this issue](https://github.com/wp-graphql/wp-graphql/issues/1658) is same cause.

**Comment by justlevine** [comment] 2023-06-17 11:23
(duplicate of #2492 - leaving both open, since this has the PR attached)

**Closed** 2023-10-10 16:17 UTC
Labels: type: bug, Duplicate, status: in progress, scope: i18n
