### ISSUE TITLE
Error when creating comments on latest dev branch

### ISSUE THREAD

**Issue by paulisloud** [wp-graphql/wp-graphql#827] opened 2019-04-25 15:06 UTC
When trying to leave a comment using code that worked on 0.2.x, using the latest of 0.3.x, I get:

`
Error: GraphQL error: Variable "$input" got invalid value {"clientMutationId":"CreateComment","content":"Test","author":"Paul","authorEmail":"my@email.com","postId":"1234=","authorIp":"1.2.3.4"}; Field "postId" is not defined by type CreateCommentInput.
`

Has the API for comments changed?

**Comment by jasonbahl** [comment] 2019-04-25 15:09
@paulisloud the `postId` input changed to `commentedOn` I believe, because it can be more than just posts.

I believe I touched on this in the release notes 🤔, but if not, my apologies. That was a monster release, and clearly some regressions I didn't know about snuck through too.

Let me know if `commentedOn` works.

**Comment by paulisloud** [comment] 2019-04-25 15:15
Didn't see it in the blog post or the README, but may have missed it elsewhere.

Did a quick test on `commentedOn` and `commentOn` (it appears to be `commentOn` [here](https://github.com/wp-graphql/wp-graphql/blob/2c75ece5791b4a48e2b6c3a4a3761c78a3ceba37/src/Mutation/CommentCreate.php#L28)).

Submitting with `commentOn` does in fact submit the comment, but returns an error similar error to what I submitted [here](https://github.com/wp-graphql/wp-graphql/issues/826):

```json
 "debugMessage": "Cannot return null for non-nullable field Comment.id.",
```

**Comment by jasonbahl** [comment] 2019-04-25 15:17
🤔 

Ok. I'll take a look. Clearly we need to step up our integration test game. . .way too many regressions went unnoticed in this release. 😢

**Comment by paulisloud** [comment] 2019-04-25 15:21
Fantastic, thanks!

**Comment by jasonbahl** [comment] 2019-04-25 15:25
@paulisloud it was easy to gloss over, but it was in the Release notes here: https://github.com/wp-graphql/wp-graphql/releases/tag/v0.3.0

Under "Breaking Changes"

I'm looking into the ID thing though. See what we can find out.

**Comment by paulisloud** [comment] 2019-04-25 15:28
🤦‍♂️

**Comment by jasonbahl** [comment] 2019-04-26 14:07
@paulisloud can you provide the exact mutation(s) / query(s) you were using to get to this error? 

Trying to replicate. I _am_ seeing some funkiness, but _not_ the same as what you reported. Want to see if I can replicate your issue.

**Comment by jasonbahl** [comment] 2019-04-26 14:13
@paulisloud I think this may come down to the fact that comments can be created by non-authenticated users, but if they're not approved yet they can't be fetched by a non-authenticated user. 🤔 

So, I'm guessing you submit a comment, and ask for it in response to the mutation, but since the default status is `comment_approved: false` the Model Layer prevents the data from being returned to the user. 

Might have to think this through a bit. 

The comment _probably_ should be allowed to be returned in the response of a mutation to the user that created it, even if unauthenticated. 🤔 

Might have to work in some "ownership" logic based on IP address? 

@CodeProKid might have thoughts here 🤷‍♂️

**Comment by paulisloud** [comment] 2019-04-26 14:15
Sure, here is the mutation:

```gql
mutation CREATE_COMMENT($input: CreateCommentInput!) {
    createComment(input: $input) {
      comment {
        id
        content
        author {
          ... on CommentAuthor {
            id
            name
          }
        }
        parent {
          commentId
        }
        commentedOn {
          __typename
          ... on Post {
            postId
          }
        }
      }
    }
  }
```

And for completeness, the (beginning of the) Mutation component:

```jsx
<Mutation
  mutation={CREATE_COMMENT}
  variables={{
    input: {
      clientMutationId: "CreateComment",
      content: comment,
      author: name,
      authorEmail: email,
      commentOn: postId,
      authorIp: userIp,
      parent: props.commentReplyingToWpId
    }
  }}
>
```

**Comment by jasonbahl** [comment] 2019-04-26 14:16
@paulisloud ok thanks, this should help 😄

**Comment by paulisloud** [comment] 2019-04-26 14:19
Interesting ID on ownership. Right now (FYI), I'm passing the IP through via the client, which isn't the best obviously, so would love to have the system generate the data for me. Built that in on <0.2.4, so not sure if it's changed.

Regarding responding with the comment from the mutation, yes please! Though, do you really need to check for ownership? A mutation knows that it is a mutation, i.e. the comment mutation should simply feel fine responding to a comment mutation query with the comment content. The question of ownership doesn't (I think) even come up here, as if you mutated it, you own it.

**Comment by jasonbahl** [comment] 2019-04-26 14:25
> RE: IP
ya, I actually don't think the IP should be a mutable value. . .probably should take that out of the input and let WP create it behind the scenes 🤔 

> RE: Ownership
@paulisloud ya, realistically the user that created the comment should own it, but not all comment creators are authenticated users. You can post comments without logging in. 

The rule indeed should be that the person that posted the content should have access to see the comment when asking for it, but since they are not logged in, we can't identify them, so the Model Layer checks to see that the comment is not approved and the user that's asking for the comment does not have proper capabilities to see unapproved comments, so the Model Layer is preventing the comment from resolving. 

We don't want _all_ comments to be exposed to unauthenticated users, just the comments that have been approved. 

I think this needs a bit of thought for how to properly handle "ownership" of a comment and how the Model Layer should respect it. 

Even if we granted access to unapproved comments if your IP matched, that could allow co-workers to see each other's unapproved comments because of their shared IP, and that's a breach of privacy. 🤔 

If the user is authenticated, that's a different story, because we _can_ indeed identify them and can determine if they are the owner of the comment or have proper capabilities to see the comment they're asking to see.

**Comment by paulisloud** [comment] 2019-04-26 15:37
One thing to consider, not sure if this changes the considerations with the Model Layer or not, is that the user who submitted the comment really, from a UX standpoint (IMO), only needs to see the comment they submitted in the initial response. If they come back to the page, they should not have the expectation of seeing the comment if it has not been approved yet.

So to me its just :
* I submit the comment
* The initial mutation responds with my comment (so I can do nice UX stuff, like put the comment in the list of comments with a gray striped background or something)
* If I reload the page or come back later, I only see approved comments

(Unless I'm authenticated, in which case they would see the comment they've submitted (even if its not approved?))

**Comment by jasonbahl** [comment] 2019-04-26 16:09
@paulisloud ya, I was just thinking about this. I wonder if it's just the client's responsibility to maintain that state then? 🤔 

Like, if you're using Apollo, you could just use the values from the form submission to write to the client cache. 🤔

**Comment by paulisloud** [comment] 2019-04-26 16:24
Was thinking the same thing, however the mutation should return _something_. I am using Apollo, and it's no problem to just display the comment values myself, but just don't want an error coming back from the mutation :)

**Comment by jasonbahl** [comment] 2019-04-26 16:28
Ya...I'm still not getting the error even with the mutation you provided. 🤔

**Comment by paulisloud** [comment] 2019-04-26 16:29
Hmm, ok will do more digging on my end.

**Comment by jasonbahl** [comment] 2019-04-26 16:29
@paulisloud would you be free to hop on a Hangout so I can see your screen and get to the bottom of this? Curious if we can pinpoint the issue.

**Comment by paulisloud** [comment] 2019-04-26 16:31
Sure, let me just pull up the relevant code

**Comment by jasonbahl** [comment] 2019-04-26 16:35
Sent you a Hangout invite to your email. . .trying to ping you on Spectrum but seems like it might be down? 🤷‍♂

**Closed** 2019-04-26 20:11 UTC

**Comment by TheSolamipe** [comment] 2021-05-26 23:43
Hello @jasonbahl , trust you are doing good. 
I have been having issues using the checkout mutation, I'm getting error "Sorry, no session found " even when i try it out in the Graphiql IDE.
Can you help with this?

**Comment by TheSolamipe** [comment] 2021-05-26 23:44
Here is the mutation:

mutation CHECKOUT_MUTATION( $input: CheckoutInput! ) {
  checkout(input: $input) {
    clientMutationId
    order {
      id
      orderKey
      orderNumber
      status
      refunds {
        nodes {
          amount
        }
      }
    }
    result
    redirect
  }
}

**Comment by spencersmb** [comment] 2022-01-01 04:11
> ```js
> clientMutationId: "CreateComment",
> ```

Trying to get a comment mutation working for replying to a comment and I can't seem to get the inputs right. I can create a single comment just fine, but when trying to create a "reply" to a comment I can't get it working. I'm wondering what is supplied to the "parent" variable to get the current comment to show up as a reply.

```
mutation MyMutation {
  createComment(
    input: {
      commentOn: 5434, 
      content: "This is a test reply pending, yo", 
      author: "Jason",
      authorEmail: "spencer@gmail.com"
      parent: "Y29tbWVudDozNjY2Ng==", // ID of the comment I want to reply to but maybe thats incorrect.
    }
  ) {
    success
    comment {
      id
      content
      author {
        node {
          name
        }
      }
    }
  }
}

```

**Comment by oseisaac** [comment] 2022-07-28 03:31
> get a comment mutation working for repl

How did you resolve this ?

**Comment by shadee22** [comment] 2024-01-04 10:02
Did you fixed that?
