### ISSUE TITLE
Uncaught (in promise) GraphQLError: Names must only contain [_a-zA-Z0-9] but "Template_空白页面" does not

### ISSUE THREAD

**Issue by dxrvip** [wp-graphql/wp-graphql#2909] opened 2023-08-19 08:13 UTC
### Description

Uncaught (in promise) GraphQLError: Names must only contain [_a-zA-Z0-9] but "Template_空白页面" does not

### Steps to reproduce

Uncaught (in promise) GraphQLError: Names must only contain [_a-zA-Z0-9] but "Template_空白页面" does not

### Additional context

Uncaught (in promise) GraphQLError: Names must only contain [_a-zA-Z0-9] but "Template_空白页面" does not

### WPGraphQL Version

1.14.10版本 |

### WordPress Version

6.3

### PHP Version

7.4

### Additional enviornment details

bt

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment] 2023-08-19 08:23
Closing as duplicate of #2492.

In the future, please search the existing issues before creating a new one, and if you do create a bug report, please actually  provide the information requested in the template, instead of copy-pasting the error message several times 🙏

**Closed by justlevine** 2023-08-19 08:23 UTC
