### ISSUE TITLE
Preview doesn't work in Wp 6.2.2 and WpGrpahQL 1.14.6

### ISSUE THREAD

**Issue by DidoMarchet** [wp-graphql/wp-graphql#2844] opened 2023-07-05 08:17 UTC
### Description

Hi,
I'm trying to return the preview of a unpublished article.
But it returns null.
I use WP 6.2.2 and WPGraphQL 1.14.6.

### Steps to reproduce

Try this query with a unpublished or published article.
You can use slug or id but the result doesn't change.
```
query NewQuery {
  post(id: "YOUR_SLUG", idType: SLUG, asPreview: true) {
    id
  }
}
```

### WPGraphQL Version

1.14.6

### WordPress Version

6.2.2

### PHP Version

8.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment] 2023-07-05 11:30
Hey @DidoMarchet 

_Unpublished_ posts are not queryable by their slug, an you need to query them using their ID. This is WordPress behavior and not related to WPGraphQL.

If you're having issues querying for _published_ posts by their slug, please make sure you are querying [as an authenticated user](https://www.wpgraphql.com/docs/wp-graphiql#toggle-between-public-and-authenticated-requests).

I'm going to close this as `invalid` (that's internal maintainer-speak for "intended behavior"), but if you run into any additional issues, please feel free to open up a new bug report.

**Closed** 2023-07-05 11:31 UTC
Labels: Invalid?, close candidate

**Comment by DidoMarchet** [comment] 2023-07-05 11:36
Hi,
thanks for reply.
Even with the id it returns null.
Here an example:
<img width="1160" alt="Screenshot 2023-07-05 at 13 33 56" src="https://github.com/wp-graphql/wp-graphql/assets/38940340/2433186a-574a-4897-bc6b-da04b4b330bc">

Regards,

Davide
