### ISSUE TITLE
when i activate wpgraphql plugin with stratus theme,it will generate error. it’s not compaitible with it.

### ISSUE THREAD

**Issue by sauravsinghmind2web** [wp-graphql/wp-graphql#2960] opened 2023-10-04 04:49 UTC
### Description

when i activate wpgraphql plugin with stratus theme,it will generate error.
it’s not compaitible with it.
even if i used default theme then it’s working fine.
i am using latest wordpress 6.3.1
wpgraphql plugin 1.16.0

i got this error

Fatal error: Uncaught TypeError: Argument 4 passed to WPGraphQL\Utils\Preview::filter_post_meta_for_previews() must be of the type bool or null, array given, called in /home/1008434.cloudwaysapps.com/bmfpxanvyf/public_html/wp-includes/class-wp-hook.php on line 312 and defined in /home/1008434.cloudwaysapps.com/bmfpxanvyf/public_html/wp-content/plugins/wp-graphql/src/Utils/Preview.php:23 Stack trace: #0 /home/1008434.cloudwaysapps.com/bmfpxanvyf/public_html/wp-includes/class-wp-hook.php(312): WPGraphQL\Utils\Preview::filter_post_meta_for_previews() #1 /home/1008434.cloudwaysapps.com/bmfpxanvyf/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters() #2 /home/1008434.cloudwaysapps.com/bmfpxanvyf/public_html/wp-includes/meta.php(635): apply_filters() #3 /home/1008434.cloudwaysapps.com/bmfpxanvyf/public_html/wp-includes/meta.php(574): get_metadata_raw() #4 /home/1008434.cloudwaysapps.com/bmfpxanvyf/public_html/wp-includes/post.php(2516): get_metadata() #5 /home/1008434.cloudwaysapps.com/bmfpxanvyf/public_html/wp-cont in /home/1008434.cloudwaysapps.com/bmfpxanvyf/public_html/wp-content/plugins/wp-graphql/src/Utils/Preview.php on line 23

### Steps to reproduce

1.)install wpgraphql plugin and activate it.
2.)install startus plugin and activate it.
now open your wordpress site on different browser or private windows.

### WPGraphQL Version

1.16.0 |

### WordPress Version

6.3.1

### PHP Version

7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment] 2023-10-04 08:20
Hey @sauravsinghmind2web ,

Seems (as you noted) that this is a conflict with that theme/plugin, as they are attempting to pass an array value to [`bool $single`](https://developer.wordpress.org/reference/hooks/get_meta_type_metadata/#parameters).

In fact I'm assuming you can replicate this issue without WPGraphQL at all, by adding the following snippet to your functions.php file:

```php
add_filter( 'get_post_metadata', function( $value, int $object_id, string $meta_key, bool $single ) {
  // no fatal error should be thrown if other code is compliant with https://developer.wordpress.org/reference/hooks/get_meta_type_metadata/#parameters
  return $value;
}, 10, 4 );

I recommend you contact the developers for stratus, and letting them know about the bug.

(Closing and marking as `invalid` - not because this isn't a real issue, but rather because the issue isn't with, and can't be handled by, WPGraphQL's codebase).

**Closed** 2023-10-04 08:22 UTC
Labels: type: bug, Invalid?

**Comment by sauravsinghmind2web** [comment] 2023-10-06 05:44
when i login from my subdomain using wpgraphql plugin,i can see there cookie domain is look like adnosaur.com instead of .adnosaur.com,
even i have attach
define('COOKIE_DOMAIN', ".".$_SERVER['HTTP_HOST']); in wp-config file
,it's working if i login from my main website adnosaur.com then cookie domain is look like .adnosaur.com.
why there is diffrence between cookie domain,

**Comment by justlevine** [comment] 2023-10-06 14:43
Hi @sauravsinghmind2web , I'm not sure I understood your response. 

> when i login from my subdomain using wpgraphql plugin,i can see there cookie domain is look like adnosaur.com instead of .adnosaur.com, even i have attach define('COOKIE_DOMAIN', ".".$_SERVER['HTTP_HOST']); in wp-config file ,it's working if i login from my main website adnosaur.com then cookie domain is look like .adnosaur.com. why there is diffrence between cookie domain,

Is this the same stratus conflict you reported above or a different problem? If it's a different one, please open a new bug report with some more details including replication steps. (If it's the same issue, provide that info here so we can review it and possibly reopen this ticket) 🙏
