### ISSUE TITLE
Query failing when a linked post type has a draft

### ISSUE THREAD

**Issue by andyjamesn** [wp-graphql/wp-graphql#2993] opened 2023-11-12 02:06 UTC
### Description

I have a query that is fetching all stories (post type) and within that is is getting all staff attached to the post type. I am using WPGraphQL and WPGraphQL for Advanced Custom Fields

I have added "show_in_graphql" in my custom post types. 

If one of the staff is set to draft and not published the query returns a null object and GraphQl fails

When I query the staff directly there is no issue

### Steps to reproduce

```
query storyByNameQuery($name: String) {
  stories(
    where: {name: $name}
  ) {
    edges {
      node {
        storiesStaff {
          staff {
            ... on TeamMember {
              id
            }
          }
        }
      }
    }
  }
}
```

### Additional context

Result:

![CleanShot 2023-11-12 at 02 09 13@2x](https://github.com/wp-graphql/wp-graphql/assets/54320410/0583985b-5ec7-42c2-bec3-22f948679225)

` "debugMessage": "Abstract type Story_Storiesstaff_Staff must resolve to an Object type at runtime for field Story_Storiesstaff.staff with value \"instance of WPGraphQL\\Model\\Post\", received \"null\". Either the Story_Storiesstaff_Staff type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function.",`

### WPGraphQL Version

Version 1.18.2

### WordPress Version

6.3

### PHP Version

8.0.16

### Additional environment details

Diabled all plugins except WPGraphQL and WPGraphQL for Advanced Custom Fields

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment] 2023-11-12 06:57
Hey @andyjamesn,

As you noted the issue is with WPGraphQL for ACF,  but since you didn't share any version information, I'm going to make the assumption that you're running the old `wp-graphql-acf@0.6.x` and not the v2 rewrite that is happening over in https://github.com/wp-graphql/wpgraphql-acf.

If upgrading to the latest and greatest doesn't work, then I suggest searching/opening a bug report in that plugin's repo 🙏

**Comment by clieee** [comment] 2023-11-13 20:47
I guess I posted in the wrong repo then, about my issue here, but still seems to be related on both acf and regular wp-graphql? https://github.com/wp-graphql/wp-graphql-acf/issues/292

**Comment by jasonbahl** [comment] 2023-11-14 18:12
@andyjamesn @clieee as @justlevine suggested can ya'll try the new version of WPGraphQL for ACF? https://github.com/wp-graphql/wpgraphql-acf

You can get the installable .zip from the releases page: https://github.com/wp-graphql/wpgraphql-acf/releases

Or if you're using Composer you can install from packagist: https://packagist.org/packages/wp-graphql/wpgraphql-acf

**Comment by jasonbahl** [comment] 2023-12-14 18:08
I'm going to close this as I believe it's not an issue when using the newest WPGraphQL for ACF. 

If you believe there is an issue still, please open a new issue and provide as much detail as possible to reproduce, and make sure you're on latest versions. Thanks!

**Closed by jasonbahl** 2023-12-14 18:08 UTC
Labels: Close Candidate, Status: Awaiting Author Response
