### ISSUE TITLE
contentNodes don't resolve

### ISSUE THREAD

**Issue by mishushakov** [wp-graphql/wp-graphql#2041] opened 2021-07-29 22:02 UTC
hello,
i have noticed a bug

some nodes in `contentNodes` query don't resolve

for example, querying Posts:

```graphql
query {
  contentNodes {
    edges {
      node {
        ... on Post {
          id
          title
        }
      }
    }
  }
}
```

Response:

```json
{
  "data": {
    "contentNodes": {
      "edges": [
        {
          "node": {}
        },
        {
          "node": {}
        },
        {
          "node": {}
        },
        {
          "node": {
            "id": "cG9zdDoxMjQ2",
            "title": "All formatting"
          }
        },
        {
          "node": {}
        },
        {
          "node": {
            "id": "cG9zdDo3MzQ=",
            "title": "B.S.F.R"
          }
        },
        {
          "node": {}
        },
        {
          "node": {}
        },
        {
          "node": {}
        },
        {
          "node": {}
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```

however, if i query the posts

```graphql
query {
  posts {
    edges {
      node { 
        id
        title 
      }
    }
  }
}
```

the rest of posts is displayed also

```json
{
  "data": {
    "posts": {
      "edges": [
        {
          "node": {
            "id": "cG9zdDoxMjQ2",
            "title": "All formatting"
          }
        },
        {
          "node": {
            "id": "cG9zdDo3MzQ=",
            "title": "B.S.F.R"
          }
        },
        {
          "node": {
            "id": "cG9zdDoxMjQ=",
            "title": "Become rich"
          }
        },
        {
          "node": {
            "id": "cG9zdDoxMjE=",
            "title": "Founder Manifesto"
          }
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```

**Comment by jasonbahl** [comment] 2021-07-29 22:40
@mishushakov the `contentNodes` query returns nodes of any post type. 

If you change your query to: 

```graphql
query {
  contentNodes {
    edges {
      node {
        __typename
        ... on Post {
          id
          title
        }
      }
    }
  }
}
```

You will see that the list contains more types than just posts and you can specify what fields you want based on what types they are. Your query is specifying that you _only_ want fields if the Type is a `Post`

By default, WordPress has Posts and Pages, but Custom Post Types will be included as well in the `contentNodes` query. 

Take this post type for example: 

```php
add_action( 'init', function() {

	register_post_type( 'test', [
		'label' => 'Test',
		'show_in_graphql' => true,
		'graphql_single_name' => 'Test',
		'graphql_plural_name' => 'Tests',
		'show_ui' => true,
		'public' => true,
		'supports' => [ 'title', 'editor' ]
	]);

});
```

I registered a `test` Post Type, and I have it `show_in_graphql`, and I declare that it only supports `title` and `editor`, so that means other post_type features it doesn't support, such as `author`. 

So I can do a query like so:

You could do the following, however: 

```graphql
query {
  contentNodes {
    edges {
      node {
        __typename
        id
        uri
        ... on NodeWithTitle {
          title
        }
        ...on NodeWithAuthor {
          author {
            node {
              id
              name
            }
          }
        }
      }
    }
  }
}
```

And get a response like so: 

![Screen Shot 2021-07-29 at 4 39 12 PM](https://user-images.githubusercontent.com/1260765/127574485-2d2a3bff-75ef-4efb-8462-12a1de85bbdb.png)

Here, you can see I got a `Test`, a `Page` and a `Post` and because I specified that I want the `author` for Types that have author using `...on NodeWithAuthor {` I got the `author` field returned for the `Page` and `Post`, but I did not get it returned to me for the `Test` type, which doesn't support authors.

**Comment by jasonbahl** [comment] 2021-07-29 22:42
@mishushakov I'm going to close this, as this is expected behavior. 

Love that you're exploring WPGraphQL and asking these questions! Looking forward to seeing what you create with WPGraphQL!!

**Closed by jasonbahl** 2021-07-29 22:42 UTC

**Comment by mishushakov** [comment] 2021-07-29 22:52
yeah, i've supposed that! thanks for clarifying
you can tell, i'm really deep in love with the plugin and almost hitting the limits

looking forward to contribute some small improvements when i get a chance :smile:

**Comment by mishushakov** [comment] 2021-07-29 22:55
btw. the idea here was to build search index across posts and pages, but since i've noticed content missing, i'm just querying them via `posts` and `pages`
