### ISSUE TITLE
problem with elementor in persian

### ISSUE THREAD

**Issue by sortheme** [wp-graphql/wp-graphql#2833] opened 2023-06-17 09:44 UTC
### Description

hi, when elementor is active and site language is persian, there is an error in console log in GraphiQL IDE page as follow: 

Uncaught (in promise) GraphQLError: Names must only contain [_a-zA-Z0-9] but "Template_تمام عرض المنتور" does not.
    a http://sorth.local/wp-content/plugins/wp-graphql/build/app.js?ver=2663f617f0b84d60b40c:38
    a http://sorth.local/wp-content/plugins/wp-graphql/build/app.js?ver=2663f617f0b84d60b40c:38
    q http://sorth.local/wp-content/plugins/wp-graphql/build/app.js?ver=2663f617f0b84d60b40c:38
    h http://sorth.local/wp-content/plugins/wp-graphql/build/app.js?ver=2663f617f0b84d60b40c:38
    h http://sorth.local/wp-content/plugins/wp-graphql/build/app.js?ver=2663f617f0b84d60b40c:38
    keyValMap http://sorth.local/wp-content/plugins/wp-graphql/build/app.js?ver=2663f617f0b84d60b40c:38
    buildClientSchema http://sorth.local/wp-content/plugins/wp-graphql/build/app.js?ver=2663f617f0b84d60b40c:38
    yg http://sorth.local/wp-content/plugins/wp-graphql/build/app.js?ver=2663f617f0b84d60b40c:38

### Steps to reproduce

1- find the reason of this error
2- fix this if problem is from GraphiQL plugin, if problem is from elementor we should tell them.

### Additional context

![image](https://github.com/wp-graphql/wp-graphql/assets/62182859/28eaf3c8-5cc6-47ab-9f86-f36cb9a29b79)

### WPGraphQL Version

1.14.4

### WordPress Version

6.2.2

### PHP Version

7.4.33

### Additional enviornment details

elementor version: 3.13.4
wordpress lang: fa-IR (persian)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment] 2023-06-17 11:27
Hey @sortheme - thanks for taking the time to report this!

I'm closing this as a duplicate of #2492 . If you're feeling adventurous, please feel free to test out #2808

**Closed by justlevine** 2023-06-17 11:27 UTC
Labels: type: bug, Duplicate, scope: i18n

**Comment by sortheme** [comment] 2023-06-17 15:18
i found a workaround for this: we can use a filter name "graphql_type_name".

`add_filter(
	'graphql_type_name', function ( $type_name, $new_type_name ) {
		// ob_start();
		// var_dump($type_name);
		// file_put_contents('agraphiql.txt', ob_get_clean(), FILE_APPEND);
		if($type_name == 'Template_تمام عرض المنتور'){
			return 'TemplateElementorFullWidth';
		}
		if($type_name == 'Template_پوسته'){
			return 'TemplateElementorTheme';
		}
		return $type_name;
	}, 10, 2);`
with var_dump we can see all names.
