### ISSUE TITLE
NO SCHEMA AVAILABLE in GraphiQL version 1.6.2 IDE explorer when Stackable - Gutenberg Blocks Plugin Version 2.17.4 is activated

### ISSUE THREAD

**Issue by ladycoded** [wp-graphql/wp-graphql#2067] opened 2021-08-10 02:53 UTC
It looks like this issue has been resolved for Gutenberg but is still present with Stackable - Gutenberg Blocks Plugin Version 2.17.4 in GraphiQL version 1.6.2 

I tested this by disabling this plugin and the explorer works as expected. 

Console error is noted here:
Uncaught (in promise) Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: undefined
    at r (invariant.mjs:6)
    at r (buildClientSchema.mjs:27)
    at App.js:181

**Comment by jasonbahl** [comment] 2021-08-11 14:42
@ladycoded can you share what other plugins you have active and their versions?

**Comment by ladycoded** [comment] 2021-08-11 18:15
All are enabled. If I disable Stackable - Gutenberg Blocks the explorer works properly.

Add From Server - Version 3.4.
AJAX Thumbnail Rebuild - Version 1.13
Better Search Replace - Version 1.3.4 
Co-Authors Plus - Version 3.4.8
Download Monitor - Version 4.4.4
Duplicate Page - Version 4.4.1
Enlighter - Customizable Syntax Highlighter - Version 4.4.2
Flamingo - Version 2.2.2
Google Apps Login - Version 3.4.4 
Gutenberg Version - 11.2.1
Gutenberg PDF Viewer Block - Version 1.0
Health Check & Troubleshooting - Version 1.4.5
HubSpot All-In-One Marketing - Version 8.4.9
Meta Tag Manager - Version 2.2
MetaSlider - Version 3.22.0
Optimize Database after Deleting Revisions - Version 5.0.9
Post Grid by PickPlugins - Version 2.1.10
Post Grid Pro by PickPlugins - Version 3.2.33
Public Post Preview - Version 2.9.3
Reading Time WP - Version 2.0.10
Safe Redirect Manager - Version 1.10.0
Safe SVG - Version 1.9.9
Site Kit by Google - Version 1.38.0
Stackable - Gutenberg Blocks Version 2.17.5
Ultimate Addons for Gutenberg - Version 1.24.2
WP Fastest Cache -Version 0.9.2
WP GraphQL - Version 1.6.2
Yoast SEO - Version 16.9

**Comment by jasonbahl** [comment] 2021-08-12 15:24
@ladycoded I've reproduced this issue. I'm not sure the cause yet, but I have installed Stackable in an environment that was functional, and the Schema does stop loading in GraphiQL. 

I've marked this issue as Actionable and will start to investigate.

**Comment by jasonbahl** [comment] 2022-03-03 19:55
@ladycoded sorry it's taken so long, but this has been fixed by #2262, which will be released with v1.7.0

**Closed by jasonbahl** 2022-03-03 19:55 UTC
Labels: Bug, :rocket: Actionable, ObjectType: Settings

**Comment by ladycoded** [comment] 2022-03-08 21:14
Thanks Jason!
