### ISSUE TITLE
Query custom post types by slug returns null

### ISSUE THREAD

**Issue by sboerrigter** [wp-graphql/wp-graphql#1397] opened 2020-07-23 18:48 UTC
I think I found another bug. I registered a custom post type and am trying to query a post by it's slug, but it returns `null`. When I query the same post by the ID, database ID or URI there is no problem.

### Example query
```
{
  byId: blogPostBy(id: "cG9zdDo0NQ==") {
    title
    id
    slug
  }
  bySlug: blogPostBy(slug: "test") {
    title
    id
    slug
  }
}
```

This returns:
```
{
  "data": {
    "byId": {
      "title": "Blogpost test",
      "id": "cG9zdDo0NQ==",
      "slug": "test"
    },
    "bySlug": null
  }
}
```

### Context

I registered my custom post type with the following code:

```
register_post_type('blog', [
    'graphql_plural_name' => 'blogPosts',
    'graphql_single_name' => 'blogPost',
    'has_archive' => true,
    'labels' => [
        'add_new' => 'New blog post',
        'name' => 'Blog',
        'singular_name' => 'Blog post',
    ],
    'menu_position' => 10,
    'public' => true,
    'rewrite' => ['slug' => 'blog'],
    'show_in_graphql' => true,
    'show_in_rest' => true,
    'supports' => ['editor', 'title'],
]);
```

I am using the following WordPress plugins and versions:

- WordPress 5.4.2
- WP GraphQL 0.10.3
- WP GraphiQL 1.0.1

**Comment by jasonbahl** [comment] 2020-07-24 23:09
Hmm. I can't replicate this. 

I've used the same code as you to register a post type:

![Screen Shot 2020-07-24 at 5 04 07 PM](https://user-images.githubusercontent.com/1260765/88441875-c083aa00-cdcf-11ea-8be1-c4052fb8b134.png)

Then I added post with the same title and slug as you: 

![Screen Shot 2020-07-24 at 5 04 58 PM](https://user-images.githubusercontent.com/1260765/88441910-d42f1080-cdcf-11ea-8d93-c389eca857d0.png)

And I can successfully query with your same query: 

![Screen Shot 2020-07-24 at 5 05 48 PM](https://user-images.githubusercontent.com/1260765/88441946-f7f25680-cdcf-11ea-85f7-49707bfb13e7.png)

I'm curious if there's another plugin or custom code you have that's causing underlying issues 🤔 

## Deprecated fields

One thing to note is that the `$postType . by` fields to fetch single post nodes have been deprecated and will be removed in a future release of the plugin. 

Instead I would recommend using:  

```
{
  blogPost( id: "test" idType: SLUG ) {
    title
    id
    slug
  }
}
``` 

As seen here: 

![Screen Shot 2020-07-24 at 5 08 32 PM](https://user-images.githubusercontent.com/1260765/88442068-53bcdf80-cdd0-11ea-889e-791918985572.png)

**Comment by sboerrigter** [comment] 2020-07-25 11:13
I also tested this now with all other plugins turned off (except wp-graphql and wp-graphiql) and all code in my theme commented, except the `register_posttype()` function. I still have the same issue.

I indeed ended up using `blogPost( id: "test" idType: SLUG )` instead of `blogPostBy(slug: "test")` indeed. That does work for me. I guess it is not worth fixing this if `blogPostBy()` will be removed in the future so I'll close this one.

**Comment by chrisAlwinYS** [comment] 2020-08-07 03:43
Im having the same issue with v0.11 of the plugin. I had it working with v10.2, since 10.3 the idType: SLUG looks to have broken for me. 

using the same code to register the post type as above on a clean WP install v5.4.2 with only WPGraphQL V0.11.0 and WPGraphiQL V1.0.1: 
![Screen Shot 2020-08-07 at 3 34 03 PM](https://user-images.githubusercontent.com/49703444/89606190-7d433400-d8c3-11ea-9985-3f5e97f3b736.png)

**Comment by jasonbahl** [comment] 2020-08-07 04:59
@chrisAlwinYS have you flushed your permalinks after registering the post type?

**Comment by chrisAlwinYS** [comment] 2020-08-07 09:49
@jasonbahl Yep, deactivated and reactivated the plugins, refreshed the GraphiQL page, re-written the query. Not really sure why it's happening only to custom posts types. I have been going through the differences in the repo since 0.10.2. Ill flag if I find something. I will also test on an Apache server over the weekend to try and isolate the issue, as im running valet as my local php environment.

**Comment by jasonbahl** [comment] 2020-08-07 12:14
@chrisAlwinYS can you share your CPT registration code?

**Comment by chrisAlwinYS** [comment] 2020-08-07 22:04
@jasonbahl It's the same as previously posted in this issue. 

`add_action('init', function () {

    register_post_type('blog', [
        'graphql_plural_name' => 'blogPosts',
        'graphql_single_name' => 'blogPost',
        'has_archive' => true,
        'labels' => [
            'add_new' => 'New blog post',
            'name' => 'Blog',
            'singular_name' => 'Blog post',
        ],
        'menu_position' => 10,
        'public' => true,
        'rewrite' => ['slug' => 'blog'],
        'show_in_graphql' => true,
        'show_in_rest' => true,
        'supports' => ['editor', 'title'],
    ]);

});`

**Comment by chrisAlwinYS** [comment] 2020-08-07 23:11
@jasonbahl Looking at the source code it looks like the `post_type` is not being passed as a query_vars in the `$wp` global variable. 

Line 302: src->Data->NodeResolver.php 
`$allowed_post_types = \WPGraphQL::get_allowed_post_types();

			$post_type = 'post';
			if ( isset( $this->wp->query_vars['post_type'] ) && in_array( $this->wp->query_vars['post_type'], $allowed_post_types, true ) ) {
				$post_type = $this->wp->query_vars['post_type'];
			}
			$post = get_page_by_path( $this->wp->query_vars['name'], 'OBJECT', $post_type );
			return ! empty( $post ) ? $this->context->get_loader( 'post' )->load_deferred( $post->ID ) : null;`

therefore its running the function `get_page_by_path` with the default `post_type` value "post"

**Comment by e10jc** [comment] 2020-08-13 01:18
I have having this same exact problem, and it has nothing to do with custom posts. As you can see, querying for a single post by slug is broken; yet querying for multiple posts by slug is working as expected.

![image](https://user-images.githubusercontent.com/80369/90083682-114c3b80-dcc8-11ea-90c5-020f137122fa.png)

**Comment by chrisAlwinYS** [comment] 2020-08-13 20:53
@e10jc What version of the ACF plugin are you running?

**Comment by jasonbahl** [comment] 2020-08-15 22:53
I'm re-opening this. Getting reports on slack as well. 

Looking into this now.

**Comment by e10jc** [comment] 2020-08-16 13:53
> @e10jc What version of the WPGraphQL plugin are you running?

I tried the latest from master; the issue persists. Now I went back down to 0.10.2 and the issue is not there.

**Comment by seagyn** [comment] 2020-08-16 21:15
I can confirm that both `idTypes` `URI` and `SLUG` no longer work for me. In 10.x we fixed an issue with hierarchical URIs but the same query no longer works at all.

```query GET_POST_BY_SLUG($uri: ID!) {
      areaProfile(id: $uri idType: URI) {
        slug
      }
    }```

Give null an any URI supplied. 

If I change to slug and a non-hierarchical post type it also returns null.

**Comment by sven-ra** [comment] 2020-08-27 09:58
It seems that I can not query by Slug at all now. I am trying to query default "post" post type. It's the same for custom post types.

**Comment by chrisAlwinYS** [comment] 2020-08-27 10:43
@sven-ra I'm not seeing the same behaviour. I'm running v0.12 of the wp-graphql on WordPress 5.5. Are you running custom permalinks? or any other special settings?

**Comment by seagyn** [comment] 2020-08-27 10:45
Same is happening for me running the same version. Had to go all the way
back to 0.9 to get it to work.

**Comment by sven-ra** [comment] 2020-08-27 11:43
> @sven-ra I'm not seeing the same behaviour. I'm running v0.12 of the wp-graphql on WordPress 5.5. Are you running custom permalinks? or any other special settings?

I am running wp-graphql v0.12.1 (currently latest) and WP 5.5. I do have custom permalinks, but even when I change it back to "Post name" the problem persists.

**Comment by sven-ra** [comment] 2020-08-27 13:04
Okay did some further digging and found out that the Slug option disappears when the post type is set to hierarchical mode.

**Comment by chrisAlwinYS** [comment] 2020-08-27 20:57
Yes, that's by design. Its to prevent issues fetching posts with potentially the same "slug" but are nested.

**Comment by homerjam** [comment] 2020-08-29 14:19
> Same is happening for me running the same version. Had to go all the way back to 0.9 to get it to work.
Same here

**Comment by benknight** [comment] 2020-10-28 11:00
I'm still having this issue. Querying a non-heirarchical custom post type with id / idType "SLUG" returns null.

**Comment by justlevine** [comment] 2020-12-05 18:15
Same issue here v1.0

What's weird is that its not all items in the same CPT:
Query: 
```
query TestQuery {
  queryFromUri: guide(id: "/guides/students/ariel/about-2/", idType: URI) {
    title
    uri
    databaseId
		slug
  }
  
  queryFromSlug: guide(id: "about-2", idType:SLUG){
    title
    uri
    databaseId
    slug
  }
  
  queryFromDatabaseId: guide(id:"20387", idType:DATABASE_ID){
    title
    uri
    databaseId
    slug
  }
  
  
  queryFromUri2: guide(id: "/guides/students/biu/academics/test/", idType: URI) {
    title
    uri
    databaseId
		slug
  }
  
  queryFromSlug2: guide(id: "test", idType:SLUG){
    title
    uri
    databaseId
    slug
  }
  
  queryFromDatabaseId2: guide(id:"55503", idType:DATABASE_ID){
    title
    uri
    databaseId
    slug
  }
}
```
Result:
```
{
  "data": {
    "queryFromUri": null,
    "queryFromSlug": null,
    "queryFromDatabaseId": {
      "title": "About Ariel University",
      "uri": "/guides/students/ariel/about-2/",
      "databaseId": 20387,
      "slug": "about-2"
    },
    "queryFromUri2": {
      "title": "Test Guide for the GSC",
      "uri": "/guides/students/biu/academics/test/",
      "databaseId": 55503,
      "slug": "test"
    },
    "queryFromSlug2": {
      "title": "Test Guide for the GSC",
      "uri": "/guides/students/biu/academics/test/",
      "databaseId": 55503,
      "slug": "test"
    },
    "queryFromDatabaseId2": {
      "title": "Test Guide for the GSC",
      "uri": "/guides/students/biu/academics/test/",
      "databaseId": 55503,
      "slug": "test"
    }
  },
  "extensions": {
    "debug": []
  }
}
```

**Comment by Jalokim** [comment] 2020-12-13 20:09
I had the same problem. 
Updated everything, WP to 5.6, wpgraphql, + the custom post UI plugin and the ACF plugin.
Still no change, `null` on custom fields.

I finally took a look into the actual custom post I made and noticed that `Publicly Queryable` and `Public` was set to false.
When I changed to true all of a sudden the queries started working.
<img width="1096" alt="Screenshot 2020-12-13 at 21 07 01" src="https://user-images.githubusercontent.com/3883922/102022445-270d6280-3d87-11eb-9784-690fe3329801.png">

both by URI and by SLUG.
Dont know if this solves your problems but it did mine :)

**Comment by benknight** [comment] 2020-12-14 04:05
Thanks @Jalokim that solved the issue for me as well.

Heads up to plugin authors @jasonbahl - to avoid this confusion it might be a good idea to throw a mention of this on this page: https://www.wpgraphql.com/docs/custom-post-types/

Although it sounds like many of the people on this issue may be unable to query by slug due to different unrelated issues. In my case it was because `public` was set to false, however it wasn't obvious to me that this would make it impossible to query my custom post type in graphql by slug, as querying directly by ID still worked. In the end it makes sense, but still some people will be left scratching their heads for sure.

**Comment by baselakasha** [comment] 2021-02-16 14:11
I don't know if this is a good solution but this query worked for me. I am using CPT UI to manage my custom posts.


Replace "custompostname" with the custom post name you have and replace "SLUG-HERE" with the slug of the post you want.

```
query MyQuery {
  custompostname(id: "SLUG-HERE", idType: SLUG) {
    id
    content
  }
}
```

**Comment by jasonbahl** [comment] 2021-03-19 18:48
I'm still not able to replicate this issue. 

I have a feeling it's related to a combination of post_type registry details and/or permalink settings. 

I'll keep digging to see what I can find.

**Comment by jasonbahl** [comment] 2021-03-19 19:09
Ah, from what I can tell, this was actually closed by #1423

It looks like some of the comments might be related to registering the post type as `public => false`, so I updated the docs here to reflect that: https://www.wpgraphql.com/docs/custom-post-types/#public-vs-private-data

**Closed by jasonbahl** 2021-03-19 19:09 UTC
Labels: Bug, Needs to be reproduced, status: awaiting author response

**Comment by catedm** [comment] 2021-03-25 18:22
> I don't know if this is a good solution but this query worked for me. I am using CPT UI to manage my custom posts. custompostnameBy keeps returning NULL.
> 
> Replace "custompostname" with the custom post name you have and replace "SLUG-HERE" with the slug of the post you want.
> 
> ```
> query MyQuery {
>   custompostname(id: "SLUG-HERE", idType: SLUG) {
>     id
>     content
>   }
> }
> ```

@baselakasha I see that this working in the Wordpress graphql IDE using a hard coded string for the `id`. But how do you do this using a variable for the `id`?

**Comment by jasonbahl** [comment] 2021-03-25 18:27
@catedm 

```graphql
query MyQuery( $id:ID! ) {
  custompostname(id:$id, idType:SLUG) {
    id
    content
  }
}
```

Then you can use GraphiQL to test the variables like so:

![Screen Shot 2021-03-25 at 12 25 12 PM](https://user-images.githubusercontent.com/1260765/112524183-26f90780-8d65-11eb-8b71-0d33b37a22c0.png)

This translates to a `fetch` call similar to the following: 

```js
fetch('https://www.wpgraphql.com/graphql', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    query: `
      query MyQuery( $id:ID! ) {
        custompostname(id:$id, idType:SLUG) {
          id
          content
        }
      }
    `,
     variables: {
       slug: "slug-here"
     }
  }),
})
  .then(res => res.json())
  .then(res => console.log(res.data))
```

**Comment by yoryi** [comment] 2021-04-12 07:47
When the custom post type has hierarchical option, this issue is coming on my side.
Well, not sure, but the WP graphql is not showing SLUG option in this case

**Comment by justlevine** [comment] 2022-12-06 21:52
@kireSuomi hierarchical CPTs cannot be resolved by `SLUG` since you can have multiple cpts with the same slug e.g. `case/parent-one/child-one` and `case/parent-two/child-one`. Using `URI` is the correct approach here.

If you run into further trouble, please open up a new bug report.
