### ISSUE TITLE
Missing avatar or icon in GraphQL IDE UI

### ISSUE THREAD

**Issue by hatsumatsu** [wp-graphql/wp-graphql#3089] opened 2024-04-02 08:10 UTC
### Description

When disabling the avatar feature in a fresh WP installation (e.g. for privacy reasons), the authenticated request button in the GraphQL IDE UI has no icon or label.

GraphQL IDE:

<img width="247" alt="Screenshot 2024-04-02 at 10 01 46" src="https://github.com/wp-graphql/wp-graphql/assets/3452400/b0259f03-5cc9-4a42-990c-06c9c054c407">

WP settings:

<img width="419" alt="Screenshot 2024-04-02 at 10 00 04" src="https://github.com/wp-graphql/wp-graphql/assets/3452400/20bfa575-196b-4822-a07e-810eb501b5fd">

The [user dashicon](https://developer.wordpress.org/resource/dashicons/#admin-users) could be used in these cases.

### Steps to reproduce

1. Install a fresh WP
2. Go to _Settings_ → _Discussion_ → _Avatars_ and disable avatars
3. Go to _GraphQL_ → _GraphQL IDE_
4. The button has no label or icon.

### WPGraphQL Version

1.22.1

### WordPress Version

6.4.3

### PHP Version

8.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by josephfusco** [comment] 2024-04-03 15:30
Hey @hatsumatsu, thanks for reporting this! We are working on a newer version of the GraphQL IDE and have also tracked this over there (https://github.com/wp-graphql/wpgraphql-ide/issues/90)

**Comment by justlevine** [comment] 2024-04-03 15:35
> Hey @hatsumatsu, thanks for reporting this! We are working on a newer version of the GraphQL IDE and have also tracked this over there ([wp-graphql/wpgraphql-ide#90](https://github.com/wp-graphql/wpgraphql-ide/issues/90))

Confirming we also need to address this in core as a regression of #3067 , since the timeline for bringing in the new IDE isn't short-term(?)

**Comment by josephfusco** [comment] 2024-04-04 16:45
I'm unable to reproduce this using the above steps with no plugins installed except for WPGraphQL 1.22.1 using WordPress 6.5.

Please confirm you have tested without other WordPress plugins active 👍

**Comment by jasonbahl** [comment] 2024-04-04 17:09
@hatsumatsu I am also unable to reproduce. When I have "Show Avatars" setting set to "off", I still see my gravatar: 

![Image](https://github.com/wp-graphql/wp-graphql/assets/1260765/afd36800-35d5-4da5-83d9-9b33a5d5f923)

And when I'm using the IDE as a user that does not have a Gravatar, I see a fallback user icon:

![Image](https://github.com/wp-graphql/wp-graphql/assets/1260765/c665fbb9-6e78-48a3-8ae0-7a90331014d6)

**Comment by jasonbahl** [comment] 2024-04-05 19:55
> Confirming we also need to address this in core as a regression of https://github.com/wp-graphql/wp-graphql/pull/3067

@justlevine I'm not sure this actually is a regression 🤔 I've not been able to reproduce it at all.

**Comment by justlevine** [comment] 2024-04-05 20:10
> > Confirming we also need to address this in core as a regression of #3067
> 
> @justlevine I'm not sure this actually is a regression 🤔 I've not been able to reproduce it at all.

@jasonbahl I didn't test or triage, was solely responding to [this comment](https://github.com/wp-graphql/wp-graphql/issues/3089#issuecomment-2034930717) about tracking it in `wpgraphql-ide`>

**Comment by hatsumatsu** [comment] 2024-04-09 07:50
@jasonbahl Thanks for looming into this. 
It might be related to my custom starter theme that immediately disables avatars upon activation:
````
add_action( 'after_switch_theme', function() {
    update_option( 'show_avatars', '' );
} );
````
https://github.com/hatsumatsu/Port-F

If you disable avatars at a later point, the data and images might already be present in the database.

**Comment by josephfusco** [comment] 2024-04-11 18:13
@hatsumatsu Thanks for providing more info regarding your setup!
I am still having trouble reproducing this issue, however here is my suggestion for your situation - load custom styles when on the IDE page and avatars are disabled:


```php
add_action( 'enqueue_graphiql_extension', function() {
        $show_avatars = get_option( 'show_avatars' );

	if ( '0' !== $show_avatars && '' !== $show_avatars ) {
		return;
	}

	?>
	<style>
		[data-testid="auth-switch"] .toolbar-button span.ant-avatar-image::before {
			content: "\f110"; /* Dashicons user icon */
			color: #444;
			font-family: "Dashicons";
			display: inline-block;
			font-size: 20px;
			vertical-align: middle;
			margin-right: 5px;
		}
	</style>
	<?php
});
```

I hope this helps 🙌

**Comment by josephfusco** [comment] 2024-04-17 15:04
Closing this as we weren't able to reproduce this without any additional plugins active. A possible solution has been provided above. If there's evidence that this is still a bug to be addressed feel free to open a new issue with as much detail as possible (and reference this issue). Thanks!

**Closed by josephfusco** 2024-04-17 15:04 UTC
Labels: Type: Bug, Needs: Reproduction, Close Candidate, Status: Awaiting Author Response, GraphiQL
