### ISSUE TITLE
Hierarchical Menus

### ISSUE THREAD

**Issue by TheAggressive** [wp-graphql/wp-graphql#2155] opened 2021-11-16 19:26 UTC
Using the example on the WPGraphQL website using the query 

```graphql
query GET_MENU_BY_NAME {
  menu(id: "Docs Nav", idType: NAME) {
    count
    id
    databaseId
    name
    slug
    menuItems {
      nodes {
        id
        databaseId
        title
        url
        cssClasses
        description
        label
        linkRelationship
        target
        parentId
      }
    }
  }
}
```

It doesn't appear to return all the sub level menu items included in the flat list anymore (like it used too)? Just seems to display the top level items. So the function to convert to Hierarchical menus on the docs page isn't showing any results on the `children` object which is now empty. Is anyone else seeing the same?

Thanks!

**Comment by jasonbahl** [comment] 2021-12-07 20:57
@TheAggressive thanks for using WPGraphQL and thanks for opening this issue! 

There was a change to how menus resolve quite some time ago. 

Instead of being hierarchical by default, the menus are output in a flat-list, and can be turned back into hierarchy on the client. 

You can read more about this here: https://www.wpgraphql.com/docs/menus/#hierarchical-data

You might need to add a `(first:100)` argument to the `menuItems` field, like so:

```graphql
query GET_MENU_BY_NAME {
  menu(id: "Docs Nav", idType: NAME) {
    count
    id
    databaseId
    name
    slug
    menuItems(first:100) {
      nodes {
        id
        databaseId
        title
        url
        cssClasses
        description
        label
        linkRelationship
        target
        parentId
      }
    }
  }
}
```

And if your menu is bigger than 100 items, you could do a paginated query to ask for the next set of menu items. 

Can you confirm that the query is indeed returning both parent and child menu items in the flat list?

**Comment by jasonbahl** [comment] 2021-12-07 21:07
@TheAggressive fwiw, I just tested this functionality again, and can confirm that both parent and child menu items are being output in the list. 

Here's a menu I created with 2 root level items and one child:

![Screen Shot 2021-12-07 at 1 58 34 PM](https://user-images.githubusercontent.com/1260765/145105453-bd58959a-1e65-4dc0-b768-0ad7bf0e5fac.png)

And the query outputs all items, with the child referencing the parent:

![Screen Shot 2021-12-07 at 2 00 06 PM](https://user-images.githubusercontent.com/1260765/145105551-fbd15985-c109-45ce-b6aa-77978ccab3f4.png)

You still _can_ query hierarchically if you prefer, like so:

```graphql
{
  menu(id: 17, idType: DATABASE_ID) {
    name
    # by specifying I only want items with a parentDatabaseId of 0, 
    # I only get the root level menu items, then I can query 
    # their children using the `children` field. 
    menuItems(where: {parentDatabaseId: 0}) { 
      nodes {
        id
        databaseId
        label
        parentId
        parentDatabaseId
        childItems {
          nodes {
            id
            databaseId
            label
            parentId
            parentDatabaseId
          }
        }
      }
    }
  }
}
```


![Screen Shot 2021-12-07 at 2 02 30 PM](https://user-images.githubusercontent.com/1260765/145105698-c83d9450-a22d-40e0-9603-d7b55233d017.png)

----

@TheAggressive I'm going to close this, as I believe the information I've provided here should clarify things, and to my knowledge there's not a bug, just a difference in behavior that was changed in [v0.10.0](https://github.com/wp-graphql/wp-graphql/releases/tag/v0.10.0) in June 2020. 

If you're experiencing something other than described, please provide additional information and steps to reproduce.

**Closed by jasonbahl** 2021-12-07 21:07 UTC
