### ISSUE TITLE
[v0.0.21] Internal server error

### ISSUE THREAD

**Issue by cr101** [wp-graphql/wp-graphql#295] opened 2017-11-03 22:53 UTC
After upgrading to v0.0.21 I get the error below and the schema is not available either.

How do I debug this and find out what's going on?
Is there a query log extension to see a list of all the database queries?

![screenshot_51](https://user-images.githubusercontent.com/4064582/32398833-8ad16c86-c156-11e7-81ea-de1acdd9362d.jpg)

**Comment by jasonbahl** [comment] 2017-11-03 22:57
@cr101 do you have wp-graphql-insights active too? If so, update that to the current version (also pushed today). 

If you’re still having issues try with only wp-graphql active and no other plugins (or custom theme code) active to make sure it works on it’s own.

**Comment by jasonbahl** [comment] 2017-11-03 23:06
@cr101 also if you’ve written any code that filters the plugin or whatever try disabling that code to rule it out. And if it turns out that’s the issue send me the code and I could probably identify what’s not working. 

Make sure to read the release notes as well as there were some breaking changes

**Comment by cr101** [comment] 2017-11-03 23:17
I don't have any custom code and I just installed WPGraphQL Insights. 
When I open up GraphiQL the schema is not loading.

![screenshot_51](https://user-images.githubusercontent.com/4064582/32399265-826ca328-c159-11e7-8756-3a1e71cd42fb.jpg)

**Comment by cr101** [comment] 2017-11-03 23:18
I just updated the screenshot

**Comment by jasonbahl** [comment] 2017-11-03 23:25
Try with WPGraphQL as the only thing active. De-activate the insights plugin. 

If still having issues, in the main wp-graphql.php file where do_graphql_request() returns something like return $response->toArray() put “true” in the toArray and it should output more helpful errors

**Comment by cr101** [comment] 2017-11-03 23:38
I tried your two suggestions but no change. The schema is still not available

**Comment by jasonbahl** [comment] 2017-11-03 23:48
🤔 do you have xdebug active? You may need to adjust your max_nesting_level. 

I’m afk but you can see how it’s done in the tests/bootstrap.php file so our automated testing environment is setup properly

**Comment by jasonbahl** [comment] 2017-11-04 15:27
@cr101 any luck with this? Seems like a local environment issue. . .hard to help without more info on your setup. 

I just tried on a fresh WP install using `Local by Flywheel` running with these specs:

<img width="235" alt="screen shot 2017-11-04 at 9 22 53 am" src="https://user-images.githubusercontent.com/1260765/32406667-1a52ba6e-c142-11e7-9684-8156e3c152f5.png">

You can see the whole process of uploading the plugin, then visiting GraphiQL and loading the Schema here: 

![install-wp-graphql](https://user-images.githubusercontent.com/1260765/32406670-2e222732-c142-11e7-91bf-50f811944cab.gif)

I'm going to close this as I can't replicate the issue. . .but if you have more concrete info on there being an actual issue with the plugin I'm happy to re-open and help.

**Closed** 2017-11-04 20:23 UTC

**Comment by cr101** [comment] 2017-11-04 23:38
@jasonbahl The culprit is the plugin WooCommerce but I don't know why.
When I deactivated WooCommerce the GraphQl schema loaded fine in GraphiQL and I was also able to execute GraphQL queries.
I have WooCommerce 3.2.3 installed

**Comment by jasonbahl** [comment] 2017-11-04 23:47
Ok. That’s good to know. I’ll see if o can find anything that would be conflicting with WPGraphQL and WooCommerce. 🤔

**Comment by jasonbahl** [comment] 2017-11-06 15:14
@cr101 I've confirmed that I get the same error when both WooCommerce 3.2.3 and WPGraphQL are active at the same time. I don't have any leads on what the conflict is, but I've confirmed that _something_ is conflicting. 

I'll open a new issue to check it out further.
