### ISSUE TITLE
Users pagination returns `hasNextPage: false` even though there's more data to display

### ISSUE THREAD

**Issue by yossisp** [wp-graphql/wp-graphql#1071] opened 2019-12-12 14:52 UTC
This is an example of the query I'm making in the official Wordpress graphql api [playground](https://docs.wpgraphql.com/getting-started/posts/#pagination):

```
query GET_POSTS {
	users(first: 1) {
    nodes {
      slug
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
```
I get the result with 1 user  `paulisloud` and `hasNextPage` is `false`:
```
{
  "data": {
    "users": {
      "nodes": [
        {
          "slug": "paulisloud"
        },
        {
          "slug": "kellen"
        }
      ],
      "pageInfo": {
        "hasNextPage": false,
        "endCursor": "YXJyYXljb25uZWN0aW9uOjE2"
      }
    }
  }
}
```
However, there're more users because when querying `users(first: 1)` I got 2 results: paulisloud and kellen. But this doesn't make sense because `hasNextPage` was `false` in the previous query.

I expect `hasNextPage` to true when there're more users to show.

**Comment by jasonbahl** [comment] 2019-12-12 20:10
@yossisp Thanks for reporting. I've confirmed this is indeed a bug. 

Looking into it.

**Comment by jasonbahl** [comment] 2019-12-12 20:12
@yossisp I _think_ this might be a case of the demo site not having the latest WPGraphQL version. When I try this query on my local install, hasNextPage appears to be working properly. Looking into getting the demo API updated.

**Comment by jasonbahl** [comment] 2019-12-12 21:38
@yossisp This looks like it was a documentation issue. I've updated WPGraphQL on the demo server the documentation queries from, and I had to update the GraphiQL component on the docs site (#1073) as well. 

Closing this as I believe it's resolved. 

Thanks!

**Closed by jasonbahl** 2019-12-12 21:38 UTC
Labels: Bug

**Comment by dsifford** [comment] 2020-01-08 20:06
Just gave this a shot locally on an installation of my own and hasNextPage always appears false for all requests I've tried (not just users).

Installed the latest release versions of this plugin, as well as the acf and woocommerce extensions.

**Comment by dsifford** [comment] 2020-01-08 20:09
Oh and @jasonbahl, one more point that might be important is that I'm consuming this with gatsby using gatsby-source-graphql (similarly to how the wp-graphql org has in their example repo).

That might be the difference here.

One thing I'm also curious of now that I've got your attention: How is authentication handled with this approach? I have not provided wp-graphql with any auth details, yet gatsby is able to pull responses from seemingly all routes. Is this intended?

**Comment by jasonbahl** [comment] 2020-01-08 22:49
@dsifford Hey! Are you passing `first: xx` as an input on your query? If not, then `hasNextPage` will be false. You need to specify how many items you want for `hasNextPage` to be true. 

for example:

```
{
  users( first: 10) {
     pageInfo {
        hasNextPage
     }
     nodes {
       id
     }
  }
}
```
---

@dsifford WPGraphQL provides publicly exposed data to any requestor, much like your WordPress site provides it by URLs. 

What data is Gatsby accessing that you feel it shouldn't?

Users, for example, are public resources in WordPress if they have published any posts. If they have not, they are considered private and WPGraphQL respects that (or you caught a bug).

**Comment by dsifford** [comment] 2020-01-08 23:07
@jasonbahl Hah, well that would prob explain it then! I wasn't specifying any count or parameters whatsoever. I had it figured that the default was 10 and that i'd be able to page from there. Whoops! Thanks for the clarification.

Re: auth concerns... I suppose this might be out of scope and I'd be happy to report it downstream, but just from clicking around and peeking a couple response types, it's concerning to me that `products.totalSales` is publically available in the endpoint provided by `wp-graphql-woocommerce`.

I haven't done any further rigorous investigating since it was just about quitting time when I posted my comment initially, but I plan on digging in further tomorrow when I get back into work.

Nevertheless, this is some excellent work you've done here. Kudos!

**Comment by jasonbahl** [comment] 2020-01-09 04:07
@dsifford ah. For WPGraphQL for WooCommerce related stuff like exposing potentially sensitive data, I’d suggest opening an issue on that repo. 

@kidunot89 is super responsive.
