### ISSUE TITLE
SyntaxError: Unexpected end of JSON on Query for all Custom Post Types, all versions after 0.13.3

### ISSUE THREAD

**Issue by mhadaily** [wp-graphql/wp-graphql#1595] opened 2020-11-21 17:18 UTC
I search quite a bit but I didn't find this issue that's why I am reporting this, I  hope someone can give me a clue where the problem could be. 

When I upgrade WPGraphQL to any version after 0.13.3, I get this error for all custom post types. 
<a href="https://ibb.co/93KGM3j"><img src="https://i.ibb.co/x89348Q/Screenshot-2020-11-21-at-18-08-32.png" alt="Screenshot-2020-11-21-at-18-08-32" border="0" /></a>

I guess the breaking changes in version 0.14.0 could cause this issue but this seems not to be an impactful breaking change.

can anyone give me a clue where I should look for the issue? 

<a href="https://ibb.co/58G5X04"><img src="https://i.ibb.co/4TKjwqt/Screenshot-2020-11-21-at-18-17-18.png" alt="Screenshot-2020-11-21-at-18-17-18" border="0"></a>
<a href="https://ibb.co/CnPGvDc"><img src="https://i.ibb.co/30RZWQ3/Screenshot-2020-11-21-at-18-16-52.png" alt="Screenshot-2020-11-21-at-18-16-52" border="0"></a>
<a href="https://ibb.co/93KGM3j"><img src="https://i.ibb.co/x89348Q/Screenshot-2020-11-21-at-18-08-32.png" alt="Screenshot-2020-11-21-at-18-08-32" border="0"></a>
<a href="https://ibb.co/Z2hVZTd"><img src="https://i.ibb.co/sWF2B3j/Screenshot-2020-11-21-at-18-17-07.png" alt="Screenshot-2020-11-21-at-18-17-07" border="0"></a>

**Comment by jasonbahl** [comment] 2020-11-22 15:05
@mhadaily I'd recommend opening Chrome Dev Tools, executing a request in GraphiQL and inspecting the response of the request. 

Typically this error means there was some debug code leftover in a plugin and the request isn't completing. For example, if you (or a plugin you had installed) had an instance of `var_dump(); die();` in one of the field resolvers. 

You can read more about how to inspect the response (and other debugging tips) in the GraphQL Debugging docs: https://www.wpgraphql.com/docs/debugging/#unexpected-token-in-json-at-position-0.

**Comment by jasonbahl** [comment] 2020-11-25 14:25
@mhadaily wanted to see if you made any progress on troubleshooting this.

**Comment by mhadaily** [comment] 2020-11-25 23:00
@jasonbahl I am still debugging. I will keep you posted. I still have the same problem with the current version thought. I had to downgrade to a very old version which was working. I get this error when I upgrade WPGraphQL plugging, unfortunately, we have a release date on 1st December, and I will need to work with the old version until we release and I can debug it better later.

**Comment by mhadaily** [comment] 2020-11-30 11:54
> I'd recommend opening Chrome Dev Tools, executing a request in GraphiQL, and inspecting the response of the request.

I have the same issue while fetching from the browser. It seems the problem appears only when I upgrade. I am going to make a repo that you can reproduce.

**Comment by cezarneaga** [comment] 2020-12-14 08:37
i am having a similar issue with v1.0.1.
upon inspecting i see no response but the request is redirected somehow. Status code 301.

this is for a custom post type. this works in the rest api, btw.
any ideas? 
thanks!
Cezar

**Comment by jasonbahl** [comment] 2020-12-14 15:15
@cezarneaga can you list all the plugins that you have active, the WPGraphQL query you're trying to make and any other information that would be helpful in replicating your situation?

Do all GraphQL Queries lead to this same result? Or is it just queries with specific data? 

There's a chance that a plugin is performing 301 redirects for posts or something like that and is doing it in contexts it maybe shouldn't be doing it in. Very hard to say without more information though.

**Comment by cezarneaga** [comment] 2020-12-14 16:52
the problem appears only for this custom post type. the other stuff works. it is a large community with >9k members. 10 years  old, so number of plugins is high: 42. has buddypress, wpml, algolia, wise-chat, bp-members-only, post-SMTP...

**Comment by parisek** [comment] 2020-12-14 17:22
We have same problem with the custom post type, disabling WPML helped, but we need this plugin :) So just downgraded to older plugin version

**Comment by cezarneaga** [comment] 2020-12-14 23:21
i can confirm that disabling wpml related plugins solved issue

**Comment by jasonbahl** [comment] 2020-12-15 00:01
@parisek downgrading WPGraphQL or downgrading WPML solved it? Can you expand what versions of each plugin work together?

**Comment by parisek** [comment] 2020-12-15 07:53
@jasonbahl wp-graphql 0.13.3 (https://github.com/wp-graphql/wp-graphql/releases/tag/v0.13.3) and WPML current version (4.4.8) working together

Also tried downgrade WPML version (4.3.x) and current wp-graphql 1.0.1 but not working as well

**Comment by JordanaHarrison** [comment] 2021-02-08 23:22
I'm confirming that wp-graphql version 0.13.3 works with current WPML (4.4.9) but breaks at 0.14.0 and above due to 301 redirects happening because of WPML (I see X-Redirect-By: WPML in the network request, which seems to happen when it reaches a 404?). Would love a fix or workaround for this!

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by cezarneaga** [comment] 2021-02-10 23:07
Hi Jordana,
what do you mean? Could you share a gist/patch to the plugin showcasing what you did?
Thanks!
Cezar

**Comment by JordanaHarrison** [comment] 2021-02-10 23:38
@cezarneaga haha I was a bit shocked at the sudden 75 emails from github. I'll try to explain my issue and solution a bit better. 

**Some background:** My project requires wp-graphql and WPML, and I had created my own types/mutations etc to work with WPML because at the time no WPML graphql plugin existed. I based that architecture largely on the Polylang one. I was using a pretty old version of the wp-graphql plugin, so I decided to update it and then discovered that _only_ queries on posts/pages were having issues, and were returning `SyntaxError: Unexpected token < in JSON at position 0`. My taxonomy queries and mutations were still all good. I peeked at the network request for the query and saw that WPML was trigging a 302 redirect for some unknown reason, which was causing the error.

**What I tried:** I tried downgrading WPML (no luck). I tried downgrading wp-graphql (worked on versions below 0.14.0). I tried disabling WPML (also worked, but I needed it). I tried installing the https://github.com/rburgst/wp-graphql-wpml plugin (this also worked, but it interfered with the customizations I had made already). 

**What I ended up doing:** I was curious why the WPML graphql plugin worked, so I looked through the code for any differences and saw this line https://github.com/rburgst/wp-graphql-wpml/blob/master/wp-graphql-wpml.php#L405, so I implemented that in pretty much the same way they did, and now I have the current WPML and current wp-graphql working fine together.

Hope that helps!

**Comment by cezarneaga** [comment] 2021-02-15 21:03
sorry about that once again. :)

unfortunately for me activating wp-graphql-wpml throws 500s and the GraphQL plugin throws fatal error.
you wouldn't happen to work freelance? :)

**Comment by jasonbahl** [comment] 2021-03-22 23:11
I don't have a license for WPML, but I did just apply for their developer program. If I can get access to the code I'd be happy to help troubleshoot issues like this, but I'm not even vaguely familiar with the WPML codebase. 

It sounds like redirects are a primary culprit, so if we can get them resolved centrally either in WPGraphQL or WPML that would solve several issues for many users.

**Comment by mhadaily** [comment] 2021-03-29 18:37
@jasonbahl I believe you are right! because this helped me 

```php
add_filter( 'wpml_is_redirected', function( $is_redirect ) {
  if ( is_graphql_request() ) {
    return false;
  }
  return $is_redirect;
});
```
mentioned in this post https://github.com/wp-graphql/wp-graphql/issues/1626

**Comment by bhardie** [comment] 2021-05-18 17:19
Based on what @mhadaily is suggesting, this appears to be a conflict with WPML and can be resolved with the filter he shared above.

**Closed by bhardie** 2021-05-18 17:19 UTC
Labels: Bug, Extensions, WPML, close candidate, status: awaiting author response
