### ISSUE TITLE
WPGraphQL for ACF causing Gatsby build process to hang during the ingest GraphQL schema process in Docker container

### ISSUE THREAD

**Issue by alex-mmp** [wp-graphql/wp-graphql#3192] opened 2024-08-21 09:10 UTC
### Description

I have a Docker container that has a wordpress container, a mysql container for the wordpress db and a node container that runs the `gatsby build` command. When I compose up the container the builder gets stuck trying to ingest the GraphQL schema and I have to manually kill the container.

I can run the builder absolutely fine if the url for `gatsby-source-wordpress` is an endpoint hosted on a server. But when I try to use the url for the wordpress docker container (http://localhost:3000/graphql) it hangs at the ingest. I can launch the container and exec into the builder using: `docker compose run --service-ports builder bash`  and from inside the builder I'm able to curl the local host graphql endpoint without issue, even a simple query in the curl returns expected data.

I believe that the wordpress plugin WPGraphQL for ACF is causing the issue because when it is deactivated in the wordpress dashboard the gatsby build process doesn't hang at the ingest step, but completes with Graphql errors due to queries being made to ACF fields that no longer exist in the schema.

This is what the build process looks like with debug enabled and the WPGraphQL for ACF plugin activated:

```
success compile gatsby files - 2.614s
⠋ load gatsby config
  gatsby:load-themes [
  gatsby:load-themes   {
  gatsby:load-themes     themeName: 'gatsby-plugin-image',
  gatsby:load-themes     themeConfig: undefined,
  gatsby:load-themes     themeSpec: 'gatsby-plugin-image',
  gatsby:load-themes     themeDir: '/app/node_modules/gatsby-plugin-image/dist',
  gatsby:load-themes     parentDir: '/app/node_modules/gatsby-source-wordpress'
  gatsby:load-themes   },
  gatsby:load-themes   {
  gatsby:load-themes     themeName: 'gatsby-plugin-sharp',
  gatsby:load-themes     themeConfig: undefined,
  gatsby:load-themes     themeSpec: 'gatsby-plugin-sharp',
  gatsby:load-themes     themeDir: '/app/node_modules/gatsby-plugin-sharp',
  gatsby:load-themes     parentDir: '/app/node_modules/gatsby-source-wordpress'
  gatsby:load-themes   },
  gatsby:load-themes   {
  gatsby:load-themes     themeName: 'gatsby-plugin-catch-links',
  gatsby:load-themes     themeConfig: undefined,
  gatsby:load-themes     themeSpec: 'gatsby-plugin-catch-links',
  gatsby:load-themes     themeDir: '/app/node_modules/gatsby-plugin-catch-links',
  gatsby:load-themes     parentDir: '/app/node_modules/gatsby-source-wordpress'
  gatsby:load-themes   },
  gatsby:load-themes   {
  gatsby:load-themes     themeName: 'gatsby-source-wordpress',
  gatsby:load-themes     themeConfig: { plugins: [Array] },
  gatsby:load-themes     themeSpec: { resolve: 'gatsby-source-wordpress', options: [Object] },
  gatsby:load-themes     themeDir: '/app/node_modules/gatsby-source-wordpress',
  gatsby:load-themes     parentDir: '/app'
  gatsby:load-themes   },
  gatsby:load-themes   {
  gatsby:load-themes     themeName: 'gatsby-plugin-styled-components',
  gatsby:load-themes     themeConfig: undefined,
  gatsby:load-themes     themeSpec: 'gatsby-plugin-styled-components',
  gatsby:load-themes     themeDir: '/app/node_modules/gatsby-plugin-styled-components',
  gatsby:load-themes     parentDir: '/app'
  gatsby:load-themes   },
  gatsby:load-themes   {
  gatsby:load-themes     themeName: 'gatsby-plugin-image',
  gatsby:load-themes     themeConfig: undefined,
  gatsby:load-themes     themeSpec: 'gatsby-plugin-image',
  gatsby:load-themes     themeDir: '/app/node_modules/gatsby-plugin-image/dist',
  gatsby:load-themes     parentDir: '/app'
  gatsby:load-themes   },
  gatsby:load-themes   {
  gatsby:load-themes     themeName: 'gatsby-source-filesystem',
  gatsby:load-themes     themeConfig: undefined,
  gatsby:load-themes     themeSpec: { resolve: 'gatsby-source-filesystem', options: [Object] },
  gatsby:load-themes     themeDir: '/app/node_modules/gatsby-source-filesystem',
  gatsby:load-themes     parentDir: '/app'
  gatsby:load-themes   },
  gatsby:load-themes   {
  gatsby:load-themes     themeName: 'gatsby-transformer-sharp',
  gatsby:load-themes     themeConfig: undefined,
  gatsby:load-themes     themeSpec: 'gatsby-transformer-sharp',
  gatsby:load-themes     themeDir: '/app/node_modules/gatsby-transformer-sharp',
  gatsby:load-themes     parentDir: '/app'
  gatsby:load-themes   },
  gatsby:load-themes   {
  gatsby:load-themes     themeName: 'gatsby-plugin-sharp',
  gatsby:load-themes     themeConfig: undefined,
  gatsby:load-themes     themeSpec: 'gatsby-plugin-sharp',
  gatsby:load-themes     themeDir: '/app/node_modules/gatsby-plugin-sharp',
  gatsby:load-themes     parentDir: '/app'
  gatsby:load-themes   },
  gatsby:load-themes   {
  gatsby:load-themes     themeName: 'gatsby-plugin-react-helmet',
  gatsby:load-themes     themeConfig: undefined,
  gatsby:load-themes     themeSpec: 'gatsby-plugin-react-helmet',
  gatsby:load-themes     themeDir: '/app/node_modules/gatsby-plugin-react-helmet',
  gatsby:load-themes     parentDir: '/app'
  gatsby:load-themes   },
  gatsby:load-themes   {
  gatsby:load-themes     themeName: 'gatsby-plugin-google-gtag',
  gatsby:load-themes     themeConfig: undefined,
  gatsby:load-themes     themeSpec: { resolve: 'gatsby-plugin-google-gtag', options: [Object] },
  gatsby:load-themes     themeDir: '/app/node_modules/gatsby-plugin-google-gtag',
  gatsby:load-themes     parentDir: '/app'
  gatsby:load-themes   }
success load gatsby config - 0.087s

  follow-redirects options {
  maxRedirects: 21,
  maxBodyLength: 10485760,
  protocol: 'https:',
  path: '/gatsbyjs/gatsby/master/packages/gatsby/adapters.js',
  method: 'GET',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'User-Agent': 'axios/0.21.4'
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'raw.githubusercontent.com',
  port: null,
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      validateHeaderName: [Function],
      validateHeaderValue: [Function],
      get: [Function: get],
      request: [Function: request],
      setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
⠋ load plugins
<babel processes>
success load plugins - 1.586s
warn gatsby-plugin-react-helmet: Gatsby now has built-in support for modifying the document head. Learn more at https://gatsby.dev/gatsby-head
success onPreInit - 0.016s
success delete worker cache from previous builds - 0.005s
success initialize cache - 0.140s
success copy gatsby files - 0.129s
success Compiling Gatsby Functions - 0.293s
success onPreBootstrap - 0.319s
⠼ createSchemaCustomization
⠼  gatsby-source-wordpress  ensuring plugin requirements are met
  follow-redirects options {
  maxRedirects: 21,
  maxBodyLength: 10485760,
  protocol: 'http:',
  path: '/graphql',
  method: 'POST',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json',
    'User-Agent': 'axios/0.21.4',
    'Content-Length': 71
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'localhost',
  port: '3000',
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      validateHeaderName: [Function],
      validateHeaderValue: [Function],
      get: [Function: get],
      request: [Function: request],
      setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
} +3s
  follow-redirects options {
  maxRedirects: 21,
  maxBodyLength: 10485760,
  protocol: 'http:',
  path: '/graphql',
  method: 'POST',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json',
    'User-Agent': 'axios/0.21.4',
    'Content-Length': 191
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'localhost',
  port: '3000',
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      validateHeaderName: [Function],
      validateHeaderValue: [Function],
      get: [Function: get],
      request: [Function: request],
      setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
} +3ms
  follow-redirects options {
  maxRedirects: 21,
  maxBodyLength: 10485760,
  protocol: 'http:',
  path: '/graphql',
  method: 'POST',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json',
    'User-Agent': 'axios/0.21.4',
    'Content-Length': 479
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'localhost',
  port: '3000',
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      validateHeaderName: [Function],
      validateHeaderValue: [Function],
      get: [Function: get],
      request: [Function: request],
      setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
success  gatsby-source-wordpress  ensuring plugin requirements are met - 0.744s
⠏ createSchemaCustomization
⠋  gatsby-source-wordpress  ingest WPGraphQL schema
  follow-redirects options {
  maxRedirects: 21,
  maxBodyLength: 10485760,
  protocol: 'http:',
  path: '/graphql',
  method: 'POST',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json',
    'User-Agent': 'axios/0.21.4',
    'Content-Length': 233
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'localhost',
  port: '3000',
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      validateHeaderName: [Function],
      validateHeaderValue: [Function],
      get: [Function: get],
      request: [Function: request],
      setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
⠀
info  gatsby-source-wordpress

        This is either your first build or the cache was cleared.
        Please wait while your WordPress data is synced to your Gatsby cache.

        Maybe now's a good time to get up and stretch? :D

⠴ createSchemaCustomization
⠴  gatsby-source-wordpress  ingest WPGraphQL schema
  follow-redirects options {
  maxRedirects: 21,
  maxBodyLength: 10485760,
  protocol: 'http:',
  path: '/graphql',
  method: 'POST',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json',
    'User-Agent': 'axios/0.21.4',
    'Content-Length': 1219
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'localhost',
  port: '3000',
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      validateHeaderName: [Function],
      validateHeaderValue: [Function],
      get: [Function: get],
      request: [Function: request],
      setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
⠼ createSchemaCustomization
⠴  gatsby-source-wordpress  ingest WPGraphQL schema
Terminated (this is a manual termination)
```

### Steps to reproduce

1. Create a docker container, below is an example of my docker compose:
```
services:
  builder:
    build:
      context: .
    environment:
      - DEBUG=*
    ports: [ '8000:8000' ]
    links:
      - wordpress-headless
    command: npx gatsby develop -H 0.0.0.0

  wordpress-headless:
    image: ${ECR_URI}/wordpress-headless:0.0.5--alex-graphql-bug.2
    ports: [ '3000:3000' ]
    depends_on:
      wordpress-headless-mysql:
        condition: service_healthy
    links:
      - wordpress-headless-mysql

  wordpress-headless-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "<password>"
      MYSQL_DATABASE: "wordpress-headless-mysql"
    volumes:
      - ./local/my.cnf:/etc/my.cnf
      - ./local/mysql-initdb:/docker-entrypoint-initdb.d
    ports: [ "3306" ]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--connect_timeout", "1" ]
      timeout: 1s
      interval: 3s
      start_period: 3s
      retries: 10
```
2. cd into the repo in a shell and run `docker compose up --build`
3. The log entries for the builder should hang at the ingest step

### WPGraphQL Version

1.28.0

### WordPress Version

6.5.2

### PHP Version

8.2.18

### Additional environment details

**WPGraphQL for ACF**: 2.4.1
**WPGatsby**: 2.3.3
**Advanced Custom Fields PRO**: 6.3.3

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by josephfusco** [comment] 2024-08-21 16:34
Hey @alex-mmp, thanks for taking the time to open this. Are you able to interact with the GraphiQL IDE in the WordPress admin and query data? If so, there is a good chance on the Gatsby side with consuming data.

If it doesn't work in the GraphiQL IDE in WordPress, if you could share the query/response and we can dig into this more.

**Comment by alex-mmp** [comment] 2024-08-21 16:40
@josephfusco Thanks for the quick reply, I am able to access the GraphiQL IDE in the wordpress admin and conduct simple queries like getting the id for the home page. But in this IDE the ACF data isn't yet present in the schema, I would normally access the IDE at http://localhost:8000/___graphql after gatsby develop has completed to view this data.

**Comment by jasonbahl** [comment] 2024-09-11 16:09
> But in this IDE the ACF data isn't yet present in the schema, I would normally access the IDE at http://localhost:8000/___graphql after gatsby develop has completed to view this data.

If the data from ACF isn't available, do you have WPGraphQL for ACF active? The ACF data should be available in the GraphiQL IDE in the WordPress dashboard and should be queryable without Gatsby. If queries work in WordPress directly but not in Gatsby then the issue is with Gatsby and would need to be addressed on that side.

**Comment by alex-mmp** [comment] 2024-09-12 08:24
> If the data from ACF isn't available, do you have WPGraphQL for ACF active? The ACF data should be available in the GraphiQL IDE in the WordPress dashboard and should be queryable without Gatsby. If queries work in WordPress directly but not in Gatsby then the issue is with Gatsby and would need to be addressed on that side.

Apologies, I got my wires crossed before. I am able to query the ACF data in the GraphiQL IDE in WordPress. It's not that the queries don't work in Gatsby, but the fact that Gatsby just hangs using a large amount of CPU when trying to ingest the schema, causing the build not to complete. This only happens when the WPGraphQL for ACF plugin is activated so I assumed it was an issue with the plugin itself.

**Comment by jasonbahl** [comment] 2024-09-12 17:05
@alex-mmp This is almost certainly a Gatsby issue. 

The way that Gatsby works is that it reads the WPGraphQL Schema then tries to query every possible thing (post, term, etc) from WordPress given that schema. 

When you add ACF to the mix, the more fields you expose, the more things Gatsby is querying. Basically Gatsby is copying every possible piece of data from WordPress that it can to expose it to  it's GraphQL API. 

When you're querying against Gatsby's GraphQL API, you are not querying against WPGraphQL directly, you are querying against Gatsby's copy of all the data that Gatsby already fetched. 

You might be able to tailor your Gatsby Source WordPress config to limit what Gatsby is querying, reduce circular dependencies, etc (see: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#schema)

I'm going to close this as I don't believe there's an identifiable action to take on the WPGraphQL side.

**Closed by jasonbahl** 2024-09-12 17:05 UTC
Labels: close candidate, scope: extensions, gatsby
