### ISSUE TITLE
[v.1.6.7] Breaking WPGatsby data fetching.

### ISSUE THREAD

**Issue by HenrijsS** [wp-graphql/wp-graphql#2142] opened 2021-11-04 23:39 UTC
Multiple people on https://github.com/gatsbyjs/gatsby/discussions/33856 are experiencing an issue where the latest WPGraphql plugin somehow disables update detection on Gatsby's side.
There's no errors or warnings. 

Only fix for now is v1.6.6. Are there some breaking changes that keeps Gatsby from updating to the new schema? 
I see that both plugins had an update 2 days ago.

**Comment by xy-lin** [comment] 2021-11-05 08:36
WPGatsby 2.0.1 + WPGraphQL 1.6.6 works
WPGatsby 2.0.1 + WPGraphQL 1.6.7 not working: it cannot trigger the build in local `develop`. It can trigger build in hosting environment (the production build) through webhook, but the no new data is fetched.

**Comment by jasonbahl** [comment] 2021-11-05 14:31
The 1.6.7 release of WPGraphQL updated some permission checks that happen. 

If you had a post type registered to WordPress that wasn't defined to be `public=>true` or `publicly_queryable=>true` you will need to update your post_type to allow the content to be publicly exposed. 

WPGraphQL was previously exposing published content of any post_type to public users, but that's a breach of WordPress Access Control privileges, so this bug fix might require you to update how your post_type's are registered for Gatsby to pull content from them. 

See the upgrade notice here: https://github.com/wp-graphql/wp-graphql/blob/develop/readme.txt#L80-L109

You can see how WPGraphQL for WooCommerce made some changes here: https://github.com/wp-graphql/wp-graphql-woocommerce/pull/580/files

**Comment by Haldaug** [comment] 2021-11-05 15:07
I added  `publicly_queryable=>true` to my custom post types and used the following snippet to make all my pages publicy queryable too, but this didn't fix the issue. I still have to run the 1.6.6 version for my site to work properly.

```
function fix_page_query() {
    if ( post_type_exists( 'page' ) ) {
        global $wp_post_types;
        $wp_post_types['page']->publicly_queryable = true;
    }
}
add_action( 'init', 'fix_page_query', 1 );
```

**Comment by jasonbahl** [comment] 2021-11-05 15:10
@Haldaug can you query the data in graphql publicly without being authenticated? 

For example: `yoursite.com/?graphql&query={pages{nodes{id,title,content}}}`

If content is being returned by WPGraphQL, but Gatsby's not properly building, this is likely a Gatsby bug. 

If data is not returning from WPGraphQL, then we indeed do need to keep investigating on the WPGraphQL side.

**Comment by Haldaug** [comment] 2021-11-05 15:28
@jasonbahl Yes, I am able to query the data without being authenticated. I'm not sure what else could be causing this issue. Maybe something over on this end? [https://github.com/gatsbyjs/wp-gatsby/issues/200](https://github.com/gatsbyjs/wp-gatsby/issues/200)

**Comment by jasonbahl** [comment] 2021-11-05 15:29
Ok, so I just updated my WordPress install that powers WPGraphQL.com. 

I'm running:

- WPGraphQL v1.67
- WP Gatsby v2.0.1

![Screen Shot 2021-11-05 at 9 20 36 AM](https://user-images.githubusercontent.com/1260765/140534822-caec8444-158e-4ad6-b016-0c13a0bcbdbf.png)
 
 I then went to an entry in the "Documentation" post type and added a link to the content. Here's a screenshot of the revision. 
 
![Screen Shot 2021-11-05 at 9 22 02 AM](https://user-images.githubusercontent.com/1260765/140535020-51babb4c-8272-44f2-8e45-37117d680511.png)

After clicking update, I checked Gatsby Cloud and I could see that it was notified about my content update and triggered a build. 

![Screen Shot 2021-11-05 at 9 23 10 AM](https://user-images.githubusercontent.com/1260765/140535259-a59e7958-9ccf-4234-a7c6-a4df642c0f39.png)

I can manually query the content in my WordPress site by hitting this url: `https://content.wpgraphql.com/graphql?query={documents{nodes{id,databaseId,title,content}}}`

And I can see the content from my revision returned by WPGraphQL (see screenshot)

![Screen Shot 2021-11-05 at 9 26 14 AM](https://user-images.githubusercontent.com/1260765/140535854-6f64048d-9a96-4caf-bd2c-721a49132ad0.png)

But, the live page on Gatsby doesn't have my change. 

![Screen Shot 2021-11-05 at 9 27 56 AM](https://user-images.githubusercontent.com/1260765/140535944-8cf38b7b-e63a-42d9-946d-5d62e207a109.png)

From what I can tell, this is not a WPGraphQL bug. The data is there, Gatsby Cloud was notified of the change, but the change is not in my site. 🤔 

@TylerBarnes. . .any ideas here?

**Comment by jasonbahl** [comment] 2021-11-05 15:47
@Haldaug @xy-lin @HenrijsS - are ya'll using Gatsby Cloud? 

I'm using Gatsby Cloud, and it looks like my Gatsby site isn't rebuilding the pages quite right. 

When I publish content from WordPress my pages don't rebuild with the update, even though Gatsby Cloud shows the update happened in WordPress. 

But, here's another interesting thing, I released this change to content which is in a markdown file in Github, and my Gatsby site doesn't show _that_ change either. 

So I think there's something funky happening with Gatsby, not WPGraphQL, because even non-WordPress sources don't seem to be working right. 

----
fwiw, I also tried downgrading WPGatsby to v2.0.0. and 1.1.4 but no difference.

**Comment by HenrijsS** [comment] 2021-11-05 15:52
@jasonbahl I saw the issue only in development.
Haven't used Gatsby cloud at all yet.

**Comment by jasonbahl** [comment] 2021-11-05 15:55
@HenrijsS there's a chance there are multiple things happening right now. 

I would for sure make sure the content you want exposed to Gatsby is in post types that are either `public=>true` or `publicly_queryable => true`. 

If you confirm that, and there are still issues, we might have other things. 

What I and @Haldaug are experiencing, from what I can tell, seems to be on the Gatsby side, as the content is clearly changing and available in WPGraphQL (and in my case even a markdown file) but Gatsby won't pick it up 🤔

**Comment by Haldaug** [comment] 2021-11-05 15:56
@jasonbahl I see the issue both when using `gatsby build` and `gatsby develop` and on my Gatsby cloud build. Downgrading WPGraphQL to 1.6.6 fully fixes the issue for me.

**Comment by jasonbahl** [comment] 2021-11-05 15:57
🤔  very interesting.

**Comment by jasonbahl** [comment] 2021-11-05 15:59
> @jasonbahl Yes, I am able to query the data without being authenticated

Can you try in an incognito window where you are for sure not logged in? If you're logged into WordPress and just try in another tab it might be using your same session.

**Comment by HenrijsS** [comment] 2021-11-05 16:02
But the thing is that it gets the latest data.
You just need to delete the cache every time.

**Comment by jasonbahl** [comment] 2021-11-05 16:04
@HenrijsS ah, interesting. So Gatsby is getting the data from WPGraphQL but not using it to rebuild the page properly? 

You're able to get the correct data out of WPGraphQL?

**Comment by Haldaug** [comment] 2021-11-05 16:09
@jasonbahl I'm pretty sure I did test it in an incognito tab, and I can confirm that using `gatsby clean && gatsby build` fetches the new data. I can also see the correct data in the graphql IDE in WordPress.

**Comment by TylerBarnes** [comment] 2021-11-05 17:48
Fixed in WPGatsby v2.0.2

**Closed by TylerBarnes** 2021-11-05 17:48 UTC
Labels: Bug, Needs to be reproduced, Gatsby

**Comment by xy-lin** [comment] 2021-11-05 18:02
> are ya'll using Gatsby Cloud?

@jasonbahl   Yes, I am using Gatsby Cloud free tier at the moment. The problem happens with following "stack". If rolled back to  **_WPGraphQL 1.6.6_**.  Problem gone.

On WordPress side: 
WP 5.8
WPGatsby 2.0.1 
**_WPGraphQL 1.6.7_** 

Node 16.13 
react  17.0.2
Gatsby 4.1.0
gatsby-source-wordpress 6.1.0

**Comment by jasonbahl** [comment] 2021-11-05 19:38
@xy-lin can you confirm that updating WPGatsby to v2.0.2 with WPGraphQL v1.6.7 fixes this?

**Comment by Haldaug** [comment] 2021-11-05 19:56
For what it's worth, I can confirm that WPGatsby v2.0.2 with WPGraphQL v1.6.7 fixes it on my end. Plus, xy-lin has confirmed as much here: https://github.com/gatsbyjs/gatsby/discussions/33856#discussioncomment-1596807

Thank you for figuring this out together with TylerBarnes, @jasonbahl !

**Comment by HenrijsS** [comment] 2021-11-05 19:56
@jasonbahl After clearing the cache, works for me too!

**Comment by jasonbahl** [comment] 2021-11-05 19:57
Awesome! 

Sorry for the inconvenience! Glad we were able to get it working again.

**Comment by xy-lin** [comment] 2021-11-05 20:21
@jasonbahl  Yes, after upgrading WPGatsby to v2.0.2 and WPGraphQL v1.6.7 fixes both local develop build and build in Gatsby Cloud. Now any update in WordPress will trigger the build and re-fetching of data correctly as before.
Many thanks for the effort and time!

**Comment by jasonbahl** [comment] 2021-11-05 20:22
Thanks for confirming @xy-lin! 🙏🏻
