### ISSUE TITLE
Querying mediaItems via mimeTypes

### ISSUE THREAD

**Issue by cplumley** [wp-graphql/wp-graphql#1309] opened 2020-05-12 21:19 UTC
I am trying to isolate PDFs from mediaItems through mimeTypes. However, when I use the following query
```query getPdfs {
  mediaItems(where: {mimeType: APPLICATION_PDF}) {
    edges {
      node {
        id
        mimeType
      }
    }
  }
}  
```

I get back all media items
```{
  "data": {
    "mediaItems": {
      "edges": [
        {
          "node": {
            "id": "YXR0YWNobWVudDoxODA3",
            "mimeType": "image/jpeg"
          }
        },
        {
          "node": {
            "id": "YXR0YWNobWVudDoxODA2",
            "mimeType": "image/jpeg"
          }
        },
        {
          "node": {
            "id": "YXR0YWNobWVudDoxODA1",
            "mimeType": "image/jpeg"
          }
        },
        {
          "node": {
            "id": "YXR0YWNobWVudDoxODA0",
            "mimeType": "image/jpeg"
          }
        },
        {
          "node": {
            "id": "YXR0YWNobWVudDoxODAz",
            "mimeType": "image/jpeg"
          }
        },
        {
          "node": {
            "id": "YXR0YWNobWVudDo0MDA=",
            "mimeType": "image/png"
          }
        }
      ]
    }
  }
}
```

I stripped away all other plugins and moved to a default theme just to make sure there was no interference, but still run in to the issue.

WPGraphQL Version: Originally had 0.4.2, but updated to version 0.8.4 to make sure the version wasn't causing an issue.

**Comment by guidosantillan01** [comment] 2020-07-27 12:10
I am getting the same thing. 

![image](https://user-images.githubusercontent.com/6334613/88540260-e5b42a80-d012-11ea-82b2-6d637606da33.png)


@cplumley Any updates regarding your problem?

**Comment by BURROO** [comment] 2020-07-30 08:10
I am having the same issue, filtering by mimeType is not doing anything …
Did someone figure this out or found an other solution to filter files?

**Comment by cplumley** [comment] 2020-08-01 03:12
@guidosantillan01 @BURROO No updates yet. I tried looking through the source code to find a solution, but I couldn't find any reference to the mimeType options anywhere. So I am not sure where the list is coming from or how it is being parsed.

**Comment by PaulieScanlon** [comment] 2021-02-22 11:32
Hey, i'm experiencing a similar issue with `mimeType: AUDIO_MPEG`

```
{
  mediaItems(where: {mimeType: AUDIO_MPEG}) {
    edges {
      node {
        mediaItemUrl
        mimeType
      }
    }
  }
}
```

The above query returns all mediaItems regardless of `mimeType`

**Comment by dam6pl** [comment] 2021-05-31 09:40
I also have this problem. I've investigated this and the problem is in `sanitize_input_fields` method in `PostObjectConnectionResolver` class. In the `$arg_mapping` array there is no translation for `mimeType` key.

As a temporary solution this can be fixed by the filter:

```php
add_filter('graphql_map_input_fields_to_wp_query', function ($query_args) {
    if (isset($query_args['mimeType'])) {
        $query_args['post_mime_type'] = $query_args['mimeType'];
    }

    return $query_args;
});
```

**Closed** 2022-09-06 21:08 UTC
Labels: Bug, Work In Progress, ObjectType: Media, Workaround Provided
