### ISSUE TITLE
docs page not working atm

### ISSUE THREAD

**Issue by mwidmann** [wp-graphql/wp-graphql#868] opened 2019-05-28 07:21 UTC
Trying to access the docs page at https://docs.wpgrapql.com leads to and endless loop of redirects that terminates in an `ERR_TOO_MANY_REDIRECTS` in Chrome. 

In wget:

```
/tmp
❯ wget -S https://docs.wpgraphql.com/
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/mwidmann/.wget-hsts'. HSTS will be disabled.
--2019-05-28 09:18:15--  https://docs.wpgraphql.com/
Resolving docs.wpgraphql.com (docs.wpgraphql.com)... 104.18.57.143, 104.18.56.143, 2606:4700:30::6812:388f, ...
Connecting to docs.wpgraphql.com (docs.wpgraphql.com)|104.18.57.143|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 301 Moved Permanently
  Date: Tue, 28 May 2019 07:18:16 GMT
  Content-Type: text/plain
  Content-Length: 43
  Connection: keep-alive
  Set-Cookie: __cfduid=d7eb94cb6b179e14d7fc802ea16ada4881559027896; expires=Wed, 27-May-20 07:18:16 GMT; path=/; domain=.wpgraphql.com; HttpOnly
  Cache-Control: public, max-age=0, must-revalidate
  Location: https://docs.wpgraphql.com/
  X-NF-Request-ID: d89d5e94-d130-46b2-b44b-196071f35bf6-5111307
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  Server: cloudflare
  CF-RAY: 4dde74216d73cc3a-ZRH
Location: https://docs.wpgraphql.com/ [following]
--2019-05-28 09:18:16--  https://docs.wpgraphql.com/
Reusing existing connection to docs.wpgraphql.com:443.
HTTP request sent, awaiting response...
  HTTP/1.1 301 Moved Permanently
  Date: Tue, 28 May 2019 07:18:16 GMT
  Content-Type: text/plain
  Content-Length: 43
  Connection: keep-alive
  Cache-Control: public, max-age=0, must-revalidate
  Location: https://docs.wpgraphql.com/
  X-NF-Request-ID: d89d5e94-d130-46b2-b44b-196071f35bf6-5111332
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  Server: cloudflare
  CF-RAY: 4dde74219dedcc3a-ZRH

...

Location: https://docs.wpgraphql.com/ [following]
20 redirections exceeded.
```

**Comment by epeli** [comment] 2019-05-28 09:45
I'm getting this randomly in browsers too. Not able to reproduce this consistently though.

**Comment by jasonbahl** [comment] 2019-05-28 16:45
Ugh. Ya, something with my Gatsby setup on Netlify is not working. . . I've had various reports of this but haven't pinned down the issue. I believe it's something with the combination of Netlify (host for the Gatsby site) and my DNS (Cloudflare) 🤔

**Comment by jasonbahl** [comment] 2019-08-13 14:16
I made some changes to DNS a few weeks ago, and I haven't noticed any issues since. I'm closing this, but if something funky comes up again we can re-open or open a new issue.

**Closed** 2019-08-13 14:24 UTC
