### ISSUE TITLE
wpgraphql not workinq after update

### ISSUE THREAD

**Issue by saeed51100** [wp-graphql/wp-graphql#2806] opened 2023-05-05 19:41 UTC
### Description

After updating the wpgraphql plugin to version 1.14.3 in the nuxt.js project, the post link stopped working.
In other words, there is a link to the posts on the main page, but it is not transferred to the desired post.

### Steps to reproduce

**wpgraphql query:**

> query MyQuery3($uri: String!) {
            nodeByUri(uri: $uri) {
                ... on Post {
                    id
                    title
                    date
                    content
                }
            }
            }

**wpgraphql error:**

>{
  "errors": [
    {
      "message": "Variable \"$uri\" of required type \"String!\" was not provided.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 1,
          "column": 16
        }
      ]
    }
  ],
  "extensions": {
    "debug": [],
    "queryAnalyzer": {
      "keys": "79241024a199989982e5c3da37baefd048628701593ae8cd54316099bb3225dd graphql:Query operation:MyQuery3 list:post",
      "keysLength": 107,
      "keysCount": 4,
      "skippedKeys": "",
      "skippedKeysSize": 0,
      "skippedKeysCount": 0,
      "skippedTypes": []
    }
  
### Additional context

It gives the following error in the browser:

> 500
Cannot read properties of null (reading 'title')
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### WPGraphQL Version

1.14.3

### WordPress Version

6.2

### PHP Version

8.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by wildplant** [comment] 2023-05-12 16:42
me, too. rollback to 1.14.0, solved.

**Comment by saeed51100** [comment] 2023-05-13 17:17
I downloaded and installed version 1.14.0. But during activation, it gives the following error:

> Plugin could not be activated because it triggered a fatal error.
 
how to solve it?

**Comment by jasonbahl** [comment] 2023-05-24 17:28
According to the error message: `"Variable "$uri" of required type "String!" was not provided."` your query did not provide a URI as a variable. 

I'm not sure this has to do with updating / downgrading WPGraphQL. This sounds like something in the client code making queries isn't passing the `uri` variable to the query. 

If you believe there is an actual issue with WPGraphQL, I'll need clear steps to reproduce in WPGraphQL alone.

**Comment by jasonbahl** [comment] 2023-05-24 17:31
> Plugin could not be activated because it triggered a fatal error.

@saeed51100 how did you try to install it? Did you check the error logs to see what the fatal error was? There could be many reasons why a fatal error was triggered. 

For example, you could have code calling functions from WPGraphQL and when it was de-activated to activate the new one, a fatal error could have been thrown. 

You might need to make sure your custom code is wrapped with things like `if (function_exists( 'function_name' ) ) {` before calling functions from plugins. This can help protect from fatal errors when functions from plugins are called but the plugin isn't active.

There could be a number of other reasons a fatal error occurred, but we'd need more information from your error log to be able to determine what the problem is.

**Comment by jasonbahl** [comment] 2023-05-24 17:32
fwiw, I'm able to execute the query above just fine on WPGraphQL v1.14.3: 

![CleanShot 2023-05-24 at 11 32 05](https://github.com/wp-graphql/wp-graphql/assets/1260765/3679786b-8a32-4f21-9801-5061642fa101)

**Comment by jasonbahl** [comment] 2023-07-12 16:01
I'm going to close this as I wasn't able to reproduce and from what I can tell this might have been a client issue.

**Closed by jasonbahl** 2023-07-12 16:01 UTC
Labels: needs: reproduction, close candidate
