### ISSUE TITLE
Codegen issue in generating types: Interface field argument ProductWithPricing.price(format:) expected but GroupProduct.price does not provide it.

### ISSUE THREAD

**Issue by shashankitsoft** [wp-graphql/wp-graphql#3110] opened 2024-04-28 18:16 UTC
### Description

I am using PHP 8.3.3, wordpress 6.5.2, woocommerce 8.8.2, **wpgraphql** and woographql 0.19.0. Also codegen for generating types.

The latest released version **wpgraphql 1.24.0 introduced a serious bug**, which stops the generation of graphql type with codegen. 
It gives **error**: 
```
[FAILED] Interface field argument ProductWithPricing.price(format:) expected but GroupProduct.price does not provide it.
[FAILED] Interface field argument ProductUnion.description(format:) expected but ProductVariation.description does not provide it.
```

And no files are generated with codegen output.

I checked by disabling plugins one by one, but issue not gone.
**Finally I rolled back the wpgraphql to 1.23.0 and everything worked as before**, I got my graphql types generated via codegen successfully. 

**This latest wpgraphql 1.24.0 is breaking the generation, needs immediate fixing.**
cc @jasonbahl 

### Steps to reproduce

Have the environment I am using PHP 8.3.3, wordpress 6.5.2, woocommerce 8.8.2, **wpgraphql 1.24.0** and woographql 0.19.0. 
Also for the frontend in Nextjs, codegen for generating types.

Here the codegen.ts config:

```
import { CodegenConfig } from '@graphql-codegen/cli'
const config: CodegenConfig = {
  schema: process.env.NEXT_PUBLIC_GRAPHQL_ENDPOINT,
  verbose: true,
  overwrite: true,
  documents: ['graphql/**/*.graphql'],
  ignoreNoDocuments: true, // for better experience with the watcher
  generates: {
    './graphql/generated/': {
      preset: 'client',
      presetConfig: {
        fragmentMasking: false,
      },
      config: {
        namingConvention:{  // Upper-case enum keys
          enumKeys: 'change-case-all#UpperCase',
          enumValues: "keep"
        }
      },
    },
    './graphql/generated/possibleTypes.ts': {
      plugins: ['fragment-matcher'],
      config: {
        useExplicitTyping: false
      },  
    }
  }
}
export default config
```
In package.json for nextjs:
```
"scripts": {
    "dev:codegen": "graphql-codegen --watch",
}
```

Run `graphql-codegen --watch`,  or `pnpm run dev:codegen` to generate types files. 

When you use **wpgraphql 1.24.0**  it will fail to generate the types files and gives the following error:
```
[FAILED] Interface field argument ProductWithPricing.price(format:) expected but GroupProduct.price does not provide it.
[FAILED] Interface field argument ProductUnion.description(format:) expected but ProductVariation.description does not provide it.
```

Rollback plugin to **wpgraphql 1.23.0** , and rerun  `graphql-codegen --watch`,  or `pnpm run dev:codegen`. This time you will see the types files generates successfully without error.

**This latest wpgraphql 1.24.0 is breaking the generation, needs immediate fixing.**

cc @jasonbahl 

### WPGraphQL Version

1.24.0

### WordPress Version

6.5.2

### PHP Version

8.3.3

### Additional environment details

woocommerce 8.8.2 and woographql 0.19.0. NextJs 14.2 with pnpm dependency manager and codegen.ts.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment] 2024-04-29 01:47
Hey @shashankitsoft , thanks for taking the time to report this!

I believe this is a duplicate of #3108 . Would you mind testing #3109 and letting us know if it fixes the issue with Codegen?

**Comment by shashankitsoft** [comment] 2024-04-29 08:50
Hii @justlevine , yeah its seems technically related to #3108. I checked the fix of #3109 , applied over wpgraphql 1.24.0 , and seems it fixed the issue, and I got the codegen types generated as before sucessfully. 

Please merge the fix and release the updated version asap. @jasonbahl

**Comment by justlevine** [comment] 2024-04-29 09:18
Thanks for confirming! I'm going to go ahead and close this issue as a duplicate of #3108 to make it easier to track.

Ps: Jason sees all these tickets; no need to keep tagging him ;)

**Closed** 2024-04-29 09:18 UTC
Labels: Type: Bug, Duplicate, Close Candidate, Status: Awaiting Author Response, Component: Interfaces

**Comment by shashankitsoft** [comment] 2024-04-29 09:40
Sorry, tagged him just because he was making a fix for this.
You closed the ticket, okay, but when we will get the fixed version of wpgraphql released? Hoping soon.
Thanks for considering.
