### ISSUE TITLE
nodeByUri query returns nodes where URI doesn't match

### ISSUE THREAD

**Issue by andrewmumblebee** [wp-graphql/wp-graphql#2171] opened 2021-12-07 12:55 UTC
When using the nodeByUri query for grabbing any node, what i've noticed is that the query can return a result when i expect it to return nothing.

This has caused me to need to check the resulting URIs match after the response.

**Query**

```graphql
query NODE_BY_URI() {
    nodeByUri(uri: "/blog/post-without-blog-category/") {
      uri
    }
}
```

**Response**
```json
{
  "data": {
    "nodeByUri": {
      "uri": "/uncategorized/post-without-blog-category/"
    }
  }
}
```

For example i have a post with the uri `/uncategorized/new-post`, the query will return the same blog post if the `$uri` value was `/blog/new-post` which is unexpected, i'd expect that to return null, as that post is not part of the `blog` category. 

This query is great as i use it for detecting what type of nextjs template to return for the end user dynamically for any route.

For now I've added a conditional check after the request to check the response's URI for the node matches the URI that was given to the request.

WPGraphQL Version: 1.6.7

**Comment by jasonbahl** [comment] 2021-12-07 17:41
@andrewmumblebee Thanks so much for opening this issue and for using WPGraphQL in your projects!

I believe this might be a permalink settings issue. 

I've tried to recreate this scenario with the following permalinks: 

![Screen Shot 2021-12-07 at 10 27 20 AM](https://user-images.githubusercontent.com/1260765/145077224-ac7551bf-aaf7-4279-a4e2-0a484571abee.png)

Then, if I create a post with the title: `Post without blog category`, (and slug of `post-without-blog-category`) the post is available at the uri `/blog/post-without-blog-category`

I can query this in WPGraphQL and get the expected node in response, with the expected uri: 

![Screen Shot 2021-12-07 at 10 31 26 AM](https://user-images.githubusercontent.com/1260765/145077826-43ae0bcb-c986-4c76-8e71-98aa258fa83d.png)

### Reproducing the issue

I can reproduce the issue by changing my permalink settings to the following: 

![Screen Shot 2021-12-07 at 10 33 26 AM](https://user-images.githubusercontent.com/1260765/145078197-5b999beb-7984-46c9-8665-99837715d9a2.png)

With my permalinks changed to the structure above, and my WordPress Settings > Writing > Default Category set to uncategorized: 

![Screen Shot 2021-12-07 at 10 38 25 AM](https://user-images.githubusercontent.com/1260765/145078878-55e5ae00-defa-4fb5-811a-00499ba504a4.png)

Then, I am able to reproduce what you're seeing: 

![Screen Shot 2021-12-07 at 10 34 50 AM](https://user-images.githubusercontent.com/1260765/145078358-6f965e3d-6128-4aff-92b0-871a2ebfb822.png)

However, if I also visit that same uri (`/blog/post-without-blog-category/`) in a browser, WordPress itself will resolve to the updated permalink structure. 

Here's a screen recording where I put the uri `/blog/post-without-blog-category/` in my browser, and we can see that WordPress resolves to `/uncategorized/post-without-blog-category/`. 

![nodebyuri-gif](https://user-images.githubusercontent.com/1260765/145078636-0ab74fcc-c172-41de-9a8d-68ce211bd950.gif)

----

Based on how WordPress core resolves this, I believe WPGraphQL is acting as expected and that this is not a bug with WPGraphQL.

I'm going to close this issue as I believe this is expected behavior.

**Closed by jasonbahl** 2021-12-07 17:41 UTC

**Comment by andrewmumblebee** [comment] 2021-12-07 18:26
Ahhh cool, didn't realize that's how WordPress core resolves it. 

Thanks for your quick response!
