### ISSUE TITLE
404 error at /graphql endpoint (wp installation directory different from site url)

### ISSUE THREAD

**Issue by acollins1991** [wp-graphql/wp-graphql#213] opened 2017-08-31 11:10 UTC
In the WordPress general settings I have the following settings:

WordPress Address (url): mysite.com/cms
Site Address (url): mysite.com

Trying to access the graphql api at mysite.com/cms/graphql returns a 404 error and redirects to the 404 error WordPress page. Could the different in installation locaiton and site url causing this?

I'm currently using the Twenty Sixteen theme and there are two other active plugins; FakerPress and WordPress Importer.

**Comment by jasonbahl** [comment] 2017-08-31 11:53
@acollins1991 did you flush permalinks after activation? Also make sure you're permalink structure is something other than the default

**Comment by acollins1991** [comment] 2017-08-31 13:21
@jasonbahl I did originally have it set to mysite.com/%postname%/, but have changed mysite.com/post/%postname%/  with no luck. What's the simplest way to check that the endpoint is working? I've tried using postman to send JSON requests to it but would be good to see if it's just my requests that are broken rather than the endpoint. Thanks for your help!

**Comment by jasonbahl** [comment] 2017-08-31 13:29
@acollins if you visit in your browser you should see a JSON response instead of your 404 page. Also try using GraphiQL and point it at the endpoint and it should read your Schema (make sure it's using POST requests instead of GET though)

I'll check things out with a sub-directory install like you have and see what's up though

**Comment by acollins1991** [comment] 2017-08-31 15:12
@jasonbahl I have tried to use the GraphiQL Chrome Extension but only results in the following error:

`SyntaxError: Unexpected token < in JSON at position 0`

This is probably because it's receiving the 404 page rather than the expected data. 

Thanks again. Hopefully we can resolve this.

**Comment by jasonbahl** [comment] 2017-08-31 17:05
Try the GraphiQL desktop app as well, as the Chrome extension seems iffy for me too. I don't think it gets updated properly or something. . .but it sounds like there's a legit issue when the site URL is set with a directory instead of just the root.

**Comment by jasonbahl** [comment] 2017-08-31 17:05
@acollins1991 do all other pages on your site work fine with the permalink structure and site URL setup you have?

**Comment by acollins1991** [comment] 2017-09-01 18:39
@jasonbahl Couldn't get GraphiQL working unfortunately, but other posts seem ok.

**Comment by jasonbahl** [comment] 2017-09-01 18:56
@acollins1991 have you tried `mysite.com/graphql` in addition to `mysite.com/cms/graphql`?

**Comment by acollins1991** [comment] 2017-09-04 09:23
@jasonbahl Just tried mysite.com/cms/graphql and still went to the 404 page.

**Comment by jasonbahl** [comment] 2017-09-06 15:51
@acollins1991 can you also check `mysite.com/graphql`? 

If that doesn't work I'll need more info on your setup. How are you setup with your `WordPress Address` and `Site Address (url)` to be different? Whatever you have setup there _might_ have some affect on things. . .but hard to say without knowing details on how you're setup.

**Comment by acollins1991** [comment] 2017-09-07 12:30
@jasonbahl The only difference is that the WordPress installation sits in the /cms/ directory of the root domain so:

Site Address: https://root.com/
WordPress Address: https://root.com/cms/

**Comment by jasonbahl** [comment] 2017-09-07 12:55
@acollins1991 without more info, I can't be of much assistance. 

I just setup a local WordPress in a sub-directory, activated the plugin, flushed the permalinks and things are working. Attached GIF showing my site at `graphqltest.dev/cms` where `graphqltest.dev/cms/graphql` shows a 404, then I activate `WPGraphQL` and flush the permalinks, then visit `graphqltest.dev/cms/graphql` and see the JSON response, then put the URL in GraphiQL and get the schema back to explore the docs. 

![graphql-sub-directory](https://user-images.githubusercontent.com/1260765/30164363-7a5a9e80-9399-11e7-8d6f-04c8bc3737ed.gif)

It seems that things are working fine with a WordPress install in a sub-directory, such as `site.com/cms`. I'd be happy to try and help more, but I would need more info about your setup. 

I'm closing this issue as there's not enough info about your setup for me to help with. If you want to provide more info that is helpful, I'll consider re-opening and helping further.

**Closed by jasonbahl** 2017-09-07 12:55 UTC
Labels: question

**Comment by krokofant** [comment] 2017-09-13 19:03
I had the same error. Flushing the permalinks did the trick, I've never heard of it before.

Is this something that always needs to be done on clean installs?

**Comment by joshuaiz** [comment] 2019-11-29 05:06
I just ran into this after cloning a Local by Flywheel site. Flushing permalinks does fix it.

**Comment by gravityeric** [comment] 2020-01-09 06:27
Try this:

**Setting** -> **General** ->
there is two fields 
1. WordPress Address (URL)
2. Site Address (URL)

Normally we set this two fields like:
```
WordPress Address (URL) : http://example.com/main
Site Address (URL) : http://example.com 
```

And after I changed Site Address 
```
WordPress Address (URL) : http://example.com/main
Site Address (URL) : http://example.com/main
```

http://example.com/main/graphql 
works for me.

after `/graphql` was working 
you can change your Site Address (URL) back 
`Site Address (URL) : http://example.com `

**Comment by jonrrivera** [comment] 2020-03-22 00:08
thanks !

**Comment by odalton** [comment] 2020-05-08 01:19
Hi, I am having a similar issue here. Nothing to fancy in my setup running from MAMP on a mac.  `/Applications/MAMP/htdocs/wordpress/` is where the site lives.

Accessing the basic install of WP in the browser via `http://localhost:8888/wordpress` 
I have flushed the permalinks tried them in every available option `[plain, day and name, month and name, numeric, post name, custom, structure]`.

```
WordPress Address (URL): http://localhost:8888/wordpress
Site Address (URL): http://localhost:8888/wordpress
```

When I browse to the graphql endpoint `http://localhost:8888/wordpress/graphql` the site returns a HTML document with status code 200, which renders the hello world post, not a graphql JSON object as I was expecting as seen (https://www.youtube.com/watch?v=9KGuI0UmpMw).

The other plugins seem to operate fine i.e. I can query using graphiql, adv custom fields seems to work fine.

```
Advanced Custom Fields: Version 5.8.9 | By Elliot Condon
WP GraphiQL: Version 1.0.1 | By WPGraphQL, Digital First Media, Jason Bahl
WP GraphQL: Version 0.8.4 | By WPGraphQL
WPGraphQL for Advanced Custom Fields: Version 0.3.2 | By WPGraphQL, Jason Bahl
Wordpress Version : wordpress-5.4.1
```

Thanks

**Comment by geochanto** [comment] 2021-01-20 06:36
I'm running into this issue, and suggested fixes (permalink reset) did not help, unfortunately.

On my local it works fine, but for some reason on my staging server I get 404. The GraphiQL IDE inside wordpress works though...

Any other tips??

**Comment by tomatrow** [comment] 2021-07-09 22:54
So, in case the next person come along confused: try this endpoint first `http://my-wordpress-server.com?graphql=true`.

**Comment by FactoryAidan** [comment] 2021-12-20 17:29
I think the _right_ way to fix this is by creating a rule manually within WordPress to handle this parameterization; that just feels where this modification belongs.

However for the time being, I have added this `location` rule to my NGinX configuration for this virtual host:
`/etc/nginx/sites-available/my_wordpress_site.conf` and the endpoint is now working as intended.
```
location /wp/graphql {
	try_files $uri $uri/ /index.php?graphql=true&q=$uri&$args;
}
```

**Comment by jasonbahl** [comment] 2021-12-20 18:14
@FactoryAidan can you try the changes in this PR, without your nginx rule? See if that fixes things? 

https://github.com/wp-graphql/wp-graphql/pull/2182

**Comment by carlosHerz** [comment] 2022-03-12 08:58
Adding the .htaccess configurations file did the trick for me https://wordpress.org/support/article/htaccess/

**Comment by terwer** [comment] 2022-06-11 12:36
stiil not working

This is a big bug,why not fix!!!

**Comment by mahmedmushtaq** [comment] 2022-11-05 22:05
In my case, I resolved this error by 
1- by changing the permalink setting to post name
2- by generating SSL

**Comment by websuits** [comment] 2023-03-31 10:59
Permalinks solves the issue. But in my case other plugins were messing up with the schema. For other who encounter this disable other plugins and test afterwards to localise easier the problem.

**Comment by bashidagha** [comment] 2023-07-12 07:58
> So, for the next person that comes along confused: try this endpoint first `http://my-wordpress-server.com?graphql=true`.

You save my life! Thanks

**Comment by maghaffar** [comment] 2024-02-01 10:26
> @acollins1991 without more info, I can't be of much assistance.
> 
> I just setup a local WordPress in a sub-directory, activated the plugin, flushed the permalinks and things are working. Attached GIF showing my site at `graphqltest.dev/cms` where `graphqltest.dev/cms/graphql` shows a 404, then I activate `WPGraphQL` and flush the permalinks, then visit `graphqltest.dev/cms/graphql` and see the JSON response, then put the URL in GraphiQL and get the schema back to explore the docs.
> 
> ![graphql-sub-directory](https://user-images.githubusercontent.com/1260765/30164363-7a5a9e80-9399-11e7-8d6f-04c8bc3737ed.gif) [ ![graphql-sub-directory](https://user-images.githubusercontent.com/1260765/30164363-7a5a9e80-9399-11e7-8d6f-04c8bc3737ed.gif) ](https://user-images.githubusercontent.com/1260765/30164363-7a5a9e80-9399-11e7-8d6f-04c8bc3737ed.gif) [ ](https://user-images.githubusercontent.com/1260765/30164363-7a5a9e80-9399-11e7-8d6f-04c8bc3737ed.gif)
> 
> It seems that things are working fine with a WordPress install in a sub-directory, such as `site.com/cms`. I'd be happy to try and help more, but I would need more info about your setup.
> 
> I'm closing this issue as there's not enough info about your setup for me to help with. If you want to provide more info that is helpful, I'll consider re-opening and helping further.

@jasonbahl not working on my side. It works for some seconds only and after that it gives same 404 error

**Comment by justlevine** [comment] 2024-02-01 11:12
@maghaffar you quoted this part of the message but you seemed to have missed it:

> without more info, I can't be of much assistance.

Please open up a _new_ GitHub issue with the required information and enough details for a replicable test case.

**Comment by jlangz** [comment] 2024-03-10 04:03
I've resolved this by adding SSL certificate. Build step always failed without it.
