### ISSUE TITLE
Problem with sourceUrl(size: ) on mobile or mobile mode devtools

### ISSUE THREAD

**Issue by rodolphonetto** [wp-graphql/wp-graphql#1077] opened 2019-12-12 23:55 UTC
Hi guys

when doing a fetch with axios (or other) asking for a image and a especific size it works fine, but if you do that fetch from a mobile chrome or in mobile mode on chrome devtools it sends you an error: Expected type MediaItemSizeEnum, found TD_356X220.

If you run the exemple below in firefox mobile and mobile mode on devtools it also works fine, but on chrome no. If you change the TD_356X220 for MEDIUM it starts to work again

https://github.com/rodolphonetto/wpgraphql-test

To reproduce the error just clone the repo, yarn start and then press the button, it will work, then put your chrome on mobile mode on devtools and do it again, it will result the error.

**Comment by jasonbahl** [comment] 2019-12-13 01:18
@rodolphonetto can you copy how you have registered the size in WordPress?

This seems, from what I can tell, to be an issue with the client, but I want to replicate your server as well to see what I can find out.

**Comment by jasonbahl** [comment] 2019-12-13 01:58
@rodolphonetto I folllowed your steps and I cannot replicate. 

I've registered a custom image size like so: 

```
add_action( 'after_setup_theme', function() {
	add_image_size( 'td-356X220', 356, 220, false );
});
```

I confirmed it was in my Schema: 

<img width="1147" alt="Screen Shot 2019-12-12 at 6 45 41 PM" src="https://user-images.githubusercontent.com/1260765/70762965-b9f86480-1d0f-11ea-9f27-408b8cb74fc9.png">

I then confirmed I could query in GraphiQL and get expected results:

<img width="845" alt="Screen Shot 2019-12-12 at 6 46 20 PM" src="https://user-images.githubusercontent.com/1260765/70762973-c2e93600-1d0f-11ea-8ced-a2df9354a4c2.png">

I then cloned your repo, pointed it at my local install and I'm able to get results both in Desktop and Mobile (see linked screen recording: [https://cloudup.com/c0TWhEkbsOb](https://cloudup.com/c0TWhEkbsOb))

If the request works one time and not another, I would think the issue is not with the WordPress server, but rather with the client.

Hard to say for sure as I'm unable to replicate.

**Comment by rodolphonetto** [comment] 2019-12-13 02:10
@jasonbahl Thank you for the quick answer, tomorrow I'll try to register the image size as you did and try it again, what makes me sad is that it does not work only  in chrome mobile, in firefox it works, so strange 🤔

**Comment by jasonbahl** [comment] 2019-12-13 02:11
It is a very strange issue indeed. Makes me think it's somehow client related and _not_ WPGraphQL related. But happy to help if you find out that's not the case and there is indeed something in the plugin causing the issue.

**Comment by jasonbahl** [comment] 2019-12-13 02:11
@rodolphonetto I'm going to close this, but feel free to open again if you feel there's evidence something in the plugin needs to change.

**Closed by jasonbahl** 2019-12-13 02:11 UTC
Labels: Needs to be reproduced, close candidate, status: awaiting author response
