### ISSUE TITLE
Query to author with custom type content returns null

### ISSUE THREAD

**Issue by jmartinhoj** [wp-graphql/wp-graphql#1728] opened 2021-02-21 02:09 UTC
Reading wp-graphql's documentation, I understand that users without any content published in wordpress are invisible to unauthenticated queries. However, users with published content on custom types are invisible too. I think this doesn't make much sense, as it is possible to query custom types and see the "invisible" user's details but it is not possible querying user's details directly. Is there any workaround to solve this issue?

**Comment by CodeProKid** [comment] 2021-02-25 20:55
Hey @jmartinhoj, users become public if they have a published post in one of the post types that is exposed in WPGraphQL. Here is the code that handles that in the plugin: https://github.com/wp-graphql/wp-graphql/blob/6332566c3dff8370d8bf77e00be5d003e8314e20/src/Model/User.php#L144-L162

This should account for custom post types as well as core post types, my guess is that the custom post types the user has published posts in are not set to be accessible through GraphQL. Are you seeing some behavior that is different than this?

There is also a filter to change the functionality of the `private` checks within the data modeling layer here: https://github.com/wp-graphql/wp-graphql/blob/6332566c3dff8370d8bf77e00be5d003e8314e20/src/Model/Model.php#L225-L237

**Comment by romcik** [comment] 2021-06-10 15:48
Related to this topic. Users who doesn't published post, but added some comments are invisible for unauthenticated comment requests too.

```
query GetCommentsAuthor {
  comments(where: {contentId: "48059"}) {
    nodes {
      author {
        node {
          name
          isRestricted
        }
      }
    }
  }
}
```

I think, proper way to set is_private should check if user is owner of any post (as works now) or any comment.

**Comment by austins** [comment] 2021-07-01 09:59
Like @romcik said, users who haven't published any posts should be able to have their author info returned for comments on a post. For instance, the commenter may be a subscriber/member of the site, but not a contributor/author, but since they're able to comment on posts, the data for them should be returned.

**Comment by ditto-vlad** [comment] 2023-01-17 17:26
To any body trying to allow author to be queried regardless of whether they have posts published or not. This was my solution.

```php

add_filter('graphql_pre_model_data_is_private', 'pre_model_data_is_private', 10, 6);
function pre_model_data_is_private($is_private, string $model_name, $data, ?string $visibility, ?int $owner, WP_User $current_user)
{
    if (
        $model_name === 'UserObject' &&
        isset($data) && isset($data->data) && isset($data->data->is_private) && $data->data->is_private === true
    ) {
        return false;
    }

    return null;
}

add_filter('graphql_connection_query_args', 'connection_query_args', 10, 6);
function connection_query_args(array $query_args, AbstractConnectionResolver $connection_resolver, $unfiltered_args)
{

    // https://github.com/wp-graphql/wp-graphql/blob/f68ed725a753c91aabeaa59aca61d3a1f3d51ba7/src/Data/Connection/UserConnectionResolver.php#L106-L112
    if (
        isset($query_args['has_published_posts']) && $query_args['has_published_posts'] === true &&
        $connection_resolver instanceof \WPGraphQL\Data\Connection\UserConnectionResolver
    ) {
        $query_args['has_published_posts'] = null;
    }

    return $query_args;
}

```

**Comment by jasonbahl** [comment] 2024-02-17 07:23
The concept of GuestAuthor and Commentor was introduced some time ago to handle this situation of comment authors that aren't fully public users still having some fields be publicly queryable. 

I marked this as close candidate as I believe the spirit of the issue is resolved but I want to follow up with some concrete examples when I'm at my computer.

**Comment by jasonbahl** [comment] 2024-03-06 04:28
Following up here with some more context about my comment above. 

With the `Commentor` Interface, we can get public fields about a commentor, whether they're a User with no published content _or_ a Public facing user. 

To demonstrate, I've created a user, cleverly named `userWithNoContent`:

![Image](https://github.com/wp-graphql/wp-graphql/assets/1260765/53905349-e78f-4bd5-9bb9-9c075571da5a)

If we make a non-authenticated query for users, this user will not be returned in the results: 

![Image](https://github.com/wp-graphql/wp-graphql/assets/1260765/e0350353-7364-4a23-900a-b50ea5d5275c)

If we make an Authenticated request for users, this user _will_ be returned in the results:

![Image](https://github.com/wp-graphql/wp-graphql/assets/1260765/ef9bb823-9bee-4473-9b01-4995a2f36870)

Now, as this user that has no published content, I added a comment on a page:

![Image](https://github.com/wp-graphql/wp-graphql/assets/1260765/73d01faa-836f-41fa-86c3-6ac460a1af67)

As we can see, WordPress returns the name of the user along with the comment. 

And if we query for comments in WPGraphQL, we will also see that the name of the Commentor can be queried, even in a public non-authenticated query (the __typename returned is `CommentAuthor`): 

![Image](https://github.com/wp-graphql/wp-graphql/assets/1260765/3fc49bfb-e62e-40f7-855d-73afca08bcff)

But, if we make the same query as an Authenticated User, we can get the same data, _but_ the `__typename` returned is `User`

This matches the behavior of core WordPress, exposing limited fields of users publicly (i.e. their name when they are the author of a comment), while maintaining their "privacy" from other parts of the system.

**Closed by jasonbahl** 2024-03-06 04:28 UTC
Labels: Type: Enhancement, Close Candidate, ObjectType: User
