### ISSUE TITLE
No Schema and GraphQL Queries return 500 error when a custom post type word plural singular is same

### ISSUE THREAD

**Issue by rndm-user** [wp-graphql/wp-graphql#1903] opened 2021-04-29 20:51 UTC
**Issue:** The GraphQL IDE shows No Schema and all queries return 500 error.

**Reproduce:** Declare a custom post type either manually or via the Custom Posts Type UI Plugin.
and set the following to make it show show_in_graphql, 
```
'show_in_graphql' => true,
'graphql_single_name' => 'Deer',
'graphql_plural_name' => 'Deer',
```

Leaving one route off isn't an option as that also breaks things.

With the two routes not sure how to fix this but this is enough of a problem in ENGLISH, let alone other languages with different pluralization rules.  Internationalization fragility.

https://www.vappingo.com/word-blog/101-words-that-are-both-plural-and-singular/

**Workaround:** For anyone else facing this, i'm working around by adding an "s" to the plural even if that doesn't make linguistic sense.

This also seems very fragile and took me a long time to figure out what was causing the issue with no good feedback and the debug logs were no help.  At the very least checking for the issue and warning would be helpful.  Or maybe creating the plural route automatically so it isn't so fragile?  Or catching the error and just not adding an endpoint for that type until it is fixed.

having all the wpgraphql endpoints break is a pretty huge impact for properly leaving the "s" off of a pluralized word that isn't supposed to have one and could be confusing to other users as well.  especially ones where English isn't their first language.

Thanks!

**Comment by CodeProKid** [comment] 2021-05-07 16:33
Hi @rndm-user I went ahead and transferred this issue to the wp-graphql repo since it's not a WooCommerce GraphQL specific issue.

Digging into this a bit, I think the issue is that your `graphql_single_name` and `graphql_plural_name` are the same value, not that the plural name doesn't end with `s`. Take a look at the wp-graphql code that registers the schema for a post type: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Registry/TypeRegistry.php#L410-L418

These values need to be unique because we use them for registering root queries for a single query and a collection query.

**Comment by mindctrl** [comment] 2021-05-13 13:46
I'd like to propose that the plugin not throw an exception here. It can't really be caught, it potentially takes down an entire site if someone makes the mistake of supplying the same names, as the whole WPGraphQL API becomes inoperable, and the resulting 500 error is not very helpful. For users who are not developers, using things like CPT UI or similar apps to register content types, there's no way to understand the problem without getting a developer involved.

I think throwing an exception would make sense here if people were calling this method directly and had the option to catch it. But WPGraphQL is running this code automatically after someone's integration code (`register_post_type` or related filters) has already successfully executed without any notice that it was "wrong".

Not knowing this codebase, alternate ideas that come to mind are for the plugin to catch its own exception and surface errors another way, ignoring post types that were registered with duplicate names for singular/plural, or appending something to the end of the plural when duplicate names are supplied (like Collection, List, or whatever seems appropriate). In any of those scenarios, at least the WPGraphQL API doesn't become inoperable for queries unrelated to the problem.

**Comment by jasonbahl** [comment] 2021-06-22 17:31
I agree with @mindctrl that we probably shouldn't throw an exception here. 

Some options I'm thinking: 

We could leave the Types out of the Schema and output a `graphql_debug()` message which shows in the debug logs but does not cause GraphQL Errors. 

We could follow a pattern like Gatsby does where all Plurals prepend the word `all` such as `Post` and `allPost`, or could do something else like `Deer` and `DeerCollection` as @mindctrl suggested. 

So, we can let users define the single/plural themselves and if they are unique values, use them, and if plural is not populated or is the same as the `graphql_single_name` we could `prepend` so it still shows in the Schema.

**Closed** 2021-07-01 22:05 UTC
Labels: :rocket: Actionable
