### ISSUE TITLE
critical error at endpoint

### ISSUE THREAD

**Issue by amcc** [wp-graphql/wp-graphql#2487] opened 2022-08-23 16:32 UTC
### Description

/graphql endpoint is giving a wordpres: "There has been a critical error on this website." display and gatsby repots a 500 error

### Steps to reproduce

Go to /graphql on my site - error below appears (after tuning display errors to on)

Fatal error: Uncaught Error: Call to undefined method GraphQL\Type\Definition\InterfaceType::getInterfaces() in /var/www/html/wp-content/plugins/wp-graphql/src/Type/WPInterfaceTrait.php:29 Stack trace: #0 /var/www/html/wp-content/plugins/wp-graphql/src/Type/WPInterfaceType.php(119): WPGraphQL\Type\WPInterfaceType->get_implemented_interfaces() #1 /var/www/html/wp-content/plugins/wp-graphql/src/Type/WPInterfaceType.php(50): WPGraphQL\Type\WPInterfaceType->getInterfaces() #2 /var/www/html/vendor/webonyx/graphql-php/src/Type/Definition/FieldDefinition.php(80): WPGraphQL\Type\WPInterfaceType->WPGraphQL\Type\{closure}() #3 /var/www/html/vendor/webonyx/graphql-php/src/Type/Definition/InterfaceType.php(70): GraphQL\Type\Definition\FieldDefinition::defineFieldMap(Object(WPGraphQL\Type\WPInterfaceType), Object(Closure)) #4 /var/www/html/wp-content/plugins/wp-graphql/src/Utils/InstrumentSchema.php(32): GraphQL\Type\Definition\InterfaceType->getFields() #5 /var/www/html/wp-includes/class-wp-hook.php(307): WPGraphQL\Utils\InstrumentSc in /var/www/html/wp-content/plugins/wp-graphql/src/Type/WPInterfaceTrait.php on line 29

There has been a critical error on this website.

[Learn more about troubleshooting WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)

### WPGraphQL Version

1.8.6 and latest

### WordPress Version

6.0.1

### PHP Version

7.4

### Additional enviornment details

this was previously working with Version 0.7.1

update was made with WP CLI and the endpoint stopped working. The rest of the wordpress site functions ok as far as i know

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment] 2022-08-23 16:46
Sounds like an issue with the composer dependencies. Perhaps a permissions error, or feeding wp cli the path to this repo instead of the plugin directory version or wpackagist?

What happens if you _delete_ the wp-graphql plugin folder entirely and reinstall it from one of those locations?

**Comment by amcc** [comment] 2022-08-23 17:53
i did disable, then delete with wpcli, the plugin was installed ok - as in i could look at its permissions, see it on the plugins page etc. I'll see if i can reinstall again and test

**Comment by justlevine** [comment] 2022-08-23 18:16
What's the exact wpcli command you are using? Are you just doing `wp plugin install wp-graphql` or are you feeding it this repo?

**Comment by amcc** [comment] 2022-08-24 09:10
yes i used this:
```
wp plugin update wp-graphql
```

its a staging site. so i'll trash the whole thing and start again - but what would you recommend.

**Comment by justlevine** [comment] 2022-08-24 10:44
> also just tried this on a fresh install of the same site:
> 
> ```
> wp plugin install https://github.com/wp-graphql/wp-graphql/releases/download/v1.9.1/wp-graphql.zip --force
> ```
> 
> getting the same errors

There we go 😅 
You're installing it from the GitHub repo where the dependencies aren't pre built. Just do `wp plugin install wp-graphql --force` and it will download the prebuilt version from the plugin directory.

**Comment by amcc** [comment] 2022-08-24 11:00
the above command (without --force) was what i did the first time. Just tried this again with the above command and getting the same error still

**Comment by justlevine** [comment] 2022-08-24 11:08
I just tried myself and cannot replicate on a new install. 

Can you delete the plugin, run `wp cli cache clear`, and then reinstall the plugin using `wp plugin install wp-graphql --force --debug` and post the generated output?

All I can think is that it's either getting a cached version from your previous install attempts, or there's an issue with your wpcli config...

**Comment by amcc** [comment] 2022-08-24 11:16
just done that. Oddly the behaviour now is that /graphql redirects to the front page, plugin is activated and i can see the settings page fine. Here's the output.
```
user@myserver:~/html$ wp plugin install wp-graphql --force --debug
Debug (bootstrap): Fallback autoloader paths: phar://wp-cli.phar/vendor/autoload.php (0.008s)
Debug (bootstrap): Loading detected autoloader: phar://wp-cli.phar/vendor/autoload.php (0.008s)
Debug (commands): Adding command: cache (0.011s)
Debug (commands): Adding command: transient (0.011s)
Debug (commands): Adding command: comment (0.012s)
Debug (commands): Adding command: meta in comment Namespace (0.013s)
Debug (commands): Adding command: menu (0.013s)
Debug (commands): Adding command: item in menu Namespace (0.014s)
Debug (commands): Adding command: location in menu Namespace (0.014s)
Debug (commands): Deferring command: network meta (0.014s)
Debug (commands): Adding command: option (0.014s)
Debug (commands): Adding command: post (0.015s)
Debug (commands): Adding command: meta in post Namespace (0.015s)
Debug (commands): Adding command: term in post Namespace (0.016s)
Debug (commands): Adding command: post-type (0.016s)
Debug (commands): Adding command: site (0.017s)
Debug (commands): Adding command: meta in site Namespace (0.017s)
Debug (commands): Adding command: option in site Namespace (0.017s)
Debug (commands): Adding command: taxonomy (0.018s)
Debug (commands): Adding command: term (0.018s)
Debug (commands): Adding command: meta in term Namespace (0.019s)
Debug (commands): Adding command: user (0.02s)
Debug (commands): Adding command: meta in user Namespace (0.02s)
Debug (commands): Adding command: session in user Namespace (0.02s)
Debug (commands): Adding command: term in user Namespace (0.02s)
Debug (commands): Adding command: network (0.02s)
Debug (hooks): Processing hook "after_add_command:network" with 1 callbacks (0.02s)
Debug (hooks): On hook "after_add_command:network": Closure in file phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/class-wp-cli.php at line 644 (0.02s)
Debug (commands): Adding command: meta in network Namespace (0.021s)
Debug (commands): Adding command: plugin (0.023s)
Debug (commands): Adding command: auto-updates in plugin Namespace (0.023s)
Debug (commands): Adding command: theme (0.024s)
Debug (commands): Adding command: auto-updates in theme Namespace (0.024s)
Debug (commands): Adding command: mod in theme Namespace (0.024s)
Debug (commands): Adding command: db (0.026s)
Debug (commands): Adding command: scaffold (0.028s)
Debug (commands): Adding command: export (0.028s)
Debug (commands): Adding command: core (0.028s)
Debug (commands): Adding command: verify-checksums in core Namespace (0.029s)
Debug (commands): Adding command: verify-checksums in plugin Namespace (0.029s)
Debug (commands): Adding command: import (0.03s)
Debug (commands): Adding command: media (0.031s)
Debug (commands): Adding command: package (0.032s)
Debug (commands): Adding command: config (0.033s)
Debug (commands): Adding command: core (0.035s)
Debug (commands): Adding command: cron (0.035s)
Debug (commands): Adding command: event in cron Namespace (0.035s)
Debug (commands): Adding command: schedule in cron Namespace (0.036s)
Debug (commands): Adding command: embed (0.036s)
Debug (commands): Adding command: fetch in embed Namespace (0.036s)
Debug (commands): Adding command: provider in embed Namespace (0.036s)
Debug (commands): Adding command: handler in embed Namespace (0.036s)
Debug (commands): Adding command: cache in embed Namespace (0.037s)
Debug (commands): Adding command: eval (0.037s)
Debug (commands): Adding command: eval-file (0.037s)
Debug (commands): Adding command: i18n (0.037s)
Debug (commands): Adding command: make-pot in i18n Namespace (0.038s)
Debug (commands): Adding command: make-json in i18n Namespace (0.038s)
Debug (commands): Adding command: make-mo in i18n Namespace (0.038s)
Debug (commands): Deferring command: language core (0.039s)
Debug (commands): Deferring command: language plugin (0.039s)
Debug (commands): Deferring command: language theme (0.039s)
Debug (hooks): Immediately invoking on passed hook "after_add_command:site": Closure in file phar:///usr/bin/wp/vendor/wp-cli/language-command/language-command.php at line 39 (0.039s)
Debug (commands): Adding command: switch-language in site Namespace (0.04s)
Debug (commands): Adding command: language (0.04s)
Debug (hooks): Processing hook "after_add_command:language" with 3 callbacks (0.04s)
Debug (hooks): On hook "after_add_command:language": Closure in file phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/class-wp-cli.php at line 644 (0.04s)
Debug (commands): Adding command: core in language Namespace (0.04s)
Debug (hooks): On hook "after_add_command:language": Closure in file phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/class-wp-cli.php at line 644 (0.04s)
Debug (commands): Adding command: plugin in language Namespace (0.04s)
Debug (hooks): On hook "after_add_command:language": Closure in file phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/class-wp-cli.php at line 644 (0.04s)
Debug (commands): Adding command: theme in language Namespace (0.04s)
Debug (commands): Adding command: maintenance-mode (0.04s)
Debug (commands): Adding command: rewrite (0.041s)
Debug (commands): Adding command: rewrite (0.041s)
Debug (commands): Adding command: cap (0.041s)
Debug (commands): Adding command: role (0.042s)
Debug (commands): Adding command: search-replace (0.043s)
Debug (commands): Adding command: server (0.043s)
Debug (commands): Adding command: shell (0.043s)
Debug (commands): Adding command: super-admin (0.043s)
Debug (commands): Adding command: widget (0.044s)
Debug (commands): Adding command: sidebar (0.044s)
Debug (bootstrap): Adding framework command: phar://wp-cli.phar/vendor/wp-cli/wp-cli/php/commands/cli.php (0.044s)
Debug (commands): Adding command: cli (0.045s)
Debug (commands): Adding command: cache in cli Namespace (0.046s)
Debug (commands): Adding command: alias in cli Namespace (0.046s)
Debug (bootstrap): Adding framework command: phar://wp-cli.phar/vendor/wp-cli/wp-cli/php/commands/help.php (0.046s)
Debug (commands): Adding command: help (0.046s)
Debug (bootstrap): No readable global config found (0.046s)
Debug (bootstrap): No project config found (0.046s)
Debug (bootstrap): argv: /usr/bin/wp plugin install wp-graphql --force --debug (0.046s)
Debug (bootstrap): ABSPATH defined: /var/www/html/ (0.046s)
Debug (bootstrap): Begin WordPress load (0.047s)
Debug (bootstrap): wp-config.php path: /var/www/html/wp-config.php (0.048s)
Debug (commands): Adding command: acf (0.457s)
PHP Notice:  Undefined index: x-amz-bucket-region in /var/www/html/wp-content/plugins/ilab-media-tools-premium/lib/mcloud-aws/aws-sdk-php/src/S3/S3ClientTrait.php on line 219
Notice: Undefined index: x-amz-bucket-region in /var/www/html/wp-content/plugins/ilab-media-tools-premium/lib/mcloud-aws/aws-sdk-php/src/S3/S3ClientTrait.php on line 219
Debug (commands): Adding command: mediacloud:storage (0.974s)
Debug (commands): Adding command: mediacloud:vision (0.998s)
Debug (commands): Adding command: mediacloud:tasks (1.01s)
Debug (commands): Adding command: mediacloud:image-sizes (1.015s)
PHP Notice:  Undefined offset: 0 in /var/www/html/wp-content/plugins/rooftop-api-authentication/public/class-rooftop-api-authentication-public.php on line 171
Notice: Undefined offset: 0 in /var/www/html/wp-content/plugins/rooftop-api-authentication/public/class-rooftop-api-authentication-public.php on line 171
PHP Notice:  Undefined offset: 1 in /var/www/html/wp-content/plugins/rooftop-api-authentication/public/class-rooftop-api-authentication-public.php on line 171
Notice: Undefined offset: 1 in /var/www/html/wp-content/plugins/rooftop-api-authentication/public/class-rooftop-api-authentication-public.php on line 171
PHP Notice:  Undefined offset: 2 in /var/www/html/wp-content/plugins/rooftop-api-authentication/public/class-rooftop-api-authentication-public.php on line 171
Notice: Undefined offset: 2 in /var/www/html/wp-content/plugins/rooftop-api-authentication/public/class-rooftop-api-authentication-public.php on line 171
Debug (commandfactory): No doc comment for migratedb. (1.242s)
Debug (commands): Adding command: migratedb (1.243s)
Debug (bootstrap): Loaded WordPress (1.363s)
Debug (hooks): Processing hook "before_run_command" with 1 callbacks (1.363s)
Debug (hooks): On hook "before_run_command": WP_CLI\Bootstrap\RegisterDeferredCommands->add_deferred_commands() (1.363s)
Debug (bootstrap): Running command: plugin install (1.363s)
Installing WPGraphQL (1.9.1)
Downloading installation package from https://downloads.wordpress.org/plugin/wp-graphql.1.9.1.zip...
Unpacking the package...
Installing the plugin...
Removing the old version of the plugin...
Plugin updated successfully.
Success: Installed 1 of 1 plugins.
```

**Comment by justlevine** [comment] 2022-08-24 11:24
Great to hear!

> Oddly the behaviour now is that /graphql redirects to the front page

Try flushing your permalinks and disabling your other plugins (especially considering how many of them threw notices on a wholly unrelated wpcli command). Been a lot of changes since v0.7.x

**Comment by amcc** [comment] 2022-08-24 11:35
thanks for all the help so far. To be clear previously i also had graphql settings page working and it activated fine - but i got the error at the endpoint - i.e. the endpoint was there but with the critical error as above.

Currently i can't seem to get to the endpoint its still redirecting
I've gone to the permalinks setting page and get the confirmation: ```Permalink structure updated.```

Anything else to try here?

**Comment by justlevine** [comment] 2022-08-24 11:43
Disable **all your plugins** except for WPGraphQL, flush your permalinks, and try again. It will either work or provide you with a new error we can try to debug.

Assuming it works, re-enable your plugins one-by-one (flushing permalinks in between), and when it stops working again, you've found your culprit.

**Comment by justlevine** [comment] 2022-08-24 11:44
The fact that a critical error prevented the endpoint from redirecting reinforces the assumption that this is due to custom code/ a plugin conflict

**Comment by amcc** [comment] 2022-08-24 11:49
i have disabled everything except for wp-graphql. Assuming i'm flushing permalinks correctly (settings > permalinks > save). I have done this.

Same behaviour. 

Also tried uninstalling and installing another known working version we had before (1.8.6) and same behaviour (i.e. redirecting to root)

In all cases the settings page is working fine. However it looks like something is up with the endpoint. If I go to GraphiQL in the settings options it is getting no further than the spinner and this is in the console:

```
app.js?ver=ed1b92d35860129a50b81d00174fd747:30          POST https://mysite.com/index.php?graphql 500
```

**Comment by amcc** [comment] 2022-08-24 11:54
found that this url "works" with an error:
https://derby-museums-cms-update-2.onyx-sites.io/index.php?graphql

i get the same error as before at that page (at top of this thread)

**Comment by amcc** [comment] 2022-08-24 12:05
<img width="1077" alt="Screenshot 2022-08-24 at 12 59 48" src="https://user-images.githubusercontent.com/115295/186413138-8b44c8da-b8ed-4706-b3d6-724ce050c8f0.png">
response below:

`{"code":"internal_server_error","message":"<p>There has been a critical error on this website.<\/p><p><a href=\"https:\/\/wordpress.org\/support\/article\/faq-troubleshooting\/\">Learn more about troubleshooting WordPress.<\/a><\/p>","data":{"status":500},"additional_errors":[]}`

i'll try the other stuff now

**Comment by amcc** [comment] 2022-08-24 12:13
```
~/html/wp-content/plugins/wp-graphql$ composer update --no-dev --optimize-autoloader
No composer.json in current directory, do you want to use the one at /var/www/html? [Y,n]? n
Warning: This development build of Composer is over 60 days old. It is recommended to update it by running "/usr/bin/composer self-update" to get the latest version.
Composer could not find a composer.json file in /var/www/html/wp-content/plugins/wp-graphql
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage
```
I do have a composer.json at the root - i chose 'no' so didn't run that. 
This site currently doesn't enable plugins to be installed from the admin interface (i'll see if that can be enabled to test). Or were you suggesting downloading a zip and uploading to install that way? If so it looked like you suggested the command i tried earlier installing directly from github wasn't going to work - so is there a better zip:
```
wp plugin install https://github.com/wp-graphql/wp-graphql/releases/download/v1.9.1/wp-graphql.zip --force

```

**Comment by jasonbahl** [comment] 2022-08-29 22:07
@amcc can you enable WPGraphQL Debug Mode in the GraphQL Settings page?

This should give more information about the internal server error. For example you could have some PHP in a plugin that's calling an invalid function, or something along those lines. 

Check the debugging tips here: https://www.wpgraphql.com/docs/debugging/#internal-server-error

I'm going to close this, as I believe @justlevine helped resolve the original installation issue. 

Once you've gone through the debugging tips in the docs, if you're still having issues please open a new issue with details on how we can reproduce. 

Thanks! 🙏🏻

**Closed by jasonbahl** 2022-08-29 22:07 UTC
Labels: Bug, Needs to be reproduced
