### ISSUE TITLE
Internal server error when querying ACF select field when return format is set to "both"

### ISSUE THREAD

**Issue by marco910** [wp-graphql/wp-graphql#2489] opened 2022-08-30 10:09 UTC
### Description

I'm facing the same issue as described here: https://wordpress.stackexchange.com/questions/404473/acf-select-field-cant-return-array

### Steps to reproduce

Please follow the information here: https://wordpress.stackexchange.com/questions/404473/acf-select-field-cant-return-array
It's the same in my case.

### WPGraphQL Version

1.9.1

### WordPress Version

6.0.1

### PHP Version

7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment] 2022-08-30 10:24
Duplicate of https://github.com/wp-graphql/wp-graphql-acf/issues/318

**Closed by justlevine** 2022-08-30 10:24 UTC
