### ISSUE TITLE
After Update the WPgraphQL , the IDE is not working anymore

### ISSUE THREAD

**Issue by stephenwongcandr** [wp-graphql/wp-graphql#2313] opened 2022-03-29 02:06 UTC
I am using : 
Custom Post Type UI 1.10.0 
ACF Pro 5.7.12 
WPGraphQL for Advanced Custom Fields 0.5.2
and update WP GraphQL from 1.6.5 to 1.7.2
before the update, it works fine,
but after updating the WPGraphQL from 1.6.5 to 1.7.2, the IDE is not working(loading) all the time until I disable one of the above plugins, how can I fix it? since 1.6.5 have some preview bugs, it is unable to get the correct preview post data.

**Comment by bhardie** [comment] 2022-03-29 19:39
@stephenwongcandr, thank you for your report.  Which plugin do you have to deactivate to get the IDE working?  Our guess is that it is WPGraphQL for ACF.  Can you please confirm and provide a json export of your ACF field groups so we can try to reproduce?

**Comment by stephenwongcandr** [comment] 2022-03-30 01:59
hi @bhardie, when I turn off the Custom Post Type UI plugin or WPGraphQL for ACF plugin, the IDE will work again.
here is the link one time link of acf exported json:
https://file.io/l3tzImadpXQX

**Comment by sirjeff** [comment] 2022-04-04 05:07
Hi, I have a similar problem, but seems to be since upgrading to WordPress 5.9.2

When on WP 5.9.0 , I can run the GraphiQL IDE on GraphQL 1.7.2
but when on WP 5.9.2 only GraphQL 1.6.12 works

The error I am getting is
 Warning: include(...web/app/plugins/wp-graphql/build/index.asset.php): failed to open stream: No such file or directory in ...web/app/plugins/wp-graphql/src/Admin/GraphiQL/GraphiQL.php on line 132

The GrapiQL screen just has "Loading..." and it never loads.

I also have 
wp-graphql/wp-graphql-acf 0.5.3
advanced-custom-fields-pro 5.12.1
wpackagist-plugin/polylang 3.1.4
valu/wp-graphql-polylang 0.6.0

Using PHP 7.4.0 ( if that helps )

I'll try disabling some of the plugins to see if any of them are causing the issue - when I get time later today possibly.

**Comment by sirjeff** [comment] 2022-04-04 22:38
I've disabled all plugins but GraphQL and still the same error.
I then downgraded to 5.9.0 to see if it's still working and ....... nope!
So the error points to src/Admin/GraphiQL/GraphiQL.php on line 132

`$asset_file = include( WPGRAPHQL_PLUGIN_DIR . 'build/index.asset.php' );`

There is no "build" directory at plugins/wp-graphql 

If I download the package for 1.7.2 it does have the build dir. Hmmmmmm.

Confuzzled! I will clear my composer cache and try again... BBS

**Comment by sirjeff** [comment] 2022-04-04 23:05
Ok so it depends on where you get GraphQL from. I'm using Composer and both of these locations give me version 1.7.2

`wp-graphql/wp-graphql`
`wpackagist-plugin/wp-graphql`

However `wp-graphql/wp-graphql` does not have the "build" directory.

Still no go on the GraphiQL but.
Switched off all the plugins and I can see the new UI but just the loading spinner ....

No errors in the log, but getting a JavaScript error :

Uncaught (in promise) GraphQLError: Names must only contain [_a-zA-Z0-9] but "Event CodeIdType" does not.

So, yeah I have seen this before, when I first upgraded to 1.7.1

This ain't cool. I have several custom post types with spaces in the name, and that was ok in versions previous to 1.7.*

I am now going to re-write a lot of code to get around this. Sux as this is a site running in production and will cause a lot of headaches. Argh :( 

Anyway I'll be back if this is _not_ the resolve. 

::emoji_of_a_sad_cat::

**Comment by sirjeff** [comment] 2022-04-04 23:22
> Anyway I'll be back if this is _not_ the resolve.

Removing spaces in the custom post types fixed the issue :'(
These two puppies :
`graphql_single_name`
`graphql_plural_name`

**Comment by justlevine** [comment] 2022-04-05 00:10
Related: #2282

**Comment by stephenwongcandr** [comment] 2022-04-06 03:13
> > Anyway I'll be back if this is _not_ the resolve.
> 
> Removing spaces in the custom post types fixed the issue :'( These two puppies : `graphql_single_name` `graphql_plural_name`

yes ,in my case, the new version of wpgraphql and acf pro will throw the naming error in ide if you're not using camelCase,
I facing the same error when I upgrade the acf pro from 5.7.12 to  5.12.1, then I changed the name to camelCase to fix it, so I believe if you naming wrong, the new version plugin will throw some error.
also , if you using the plural_name as same as the single_name, the plural_name's query will override the single_name's query in wpgraphql.

**Comment by justlevine** [comment] 2022-04-06 03:29
My memory is clearly horrible because I was under the impression that in <1.7 you also got errors if there was a space in the name or duplicate fields... 

> if you using the plural_name as same as the single_name, the plural_name's query will override the single_name's query in wpgraphql.
@stephenwongcandr does this no longer throw a `duplicate_field` error?

**Comment by stephenwongcandr** [comment] 2022-04-06 04:04
> My memory is clearly horrible because I was under the impression that in <1.7 you also got errors if there was a space in the name or duplicate fields...
> 
> > if you using the plural_name as same as the single_name, the plural_name's query will override the single_name's query in wpgraphql.
> 
> @stephenwongcandr does this no longer throw a `duplicate_field` error?
I was using 1.6.5 and using 1.6.12 now.
I don't see that error before, it just works normally, the only problem is the single_name's query in ide is missing.

**Comment by jasonbahl** [comment] 2022-04-07 15:07
@sirjeff WPGraphQL v1.8.0 was just released this morning and is available on Composer. 

In this release, the `/build` directory is back to being versioned and included in the package that's installed from Composer. 

GraphiQL _should_ work again for folks installing via composer, without the need to run `npm install && npm run build`. 

Can you confirm that installing v1.8.0 via Composer gets you back to a functional state with GraphiQL?

**Comment by sirjeff** [comment] 2022-04-08 02:48
Yes working as advertised now :) thanky @jasonbahl 
Still got the issue with no spaces in Custom Post Type names ->
`Uncaught (in promise) GraphQLError: Names must only contain [_a-zA-Z0-9] but "Event CodeIdType" does not.`
That's fine, I've already changed the code, so no more spaces.
However I have a new issue which may or may not be related .....
... so will keep on it and see if it's me or the plugin ( or other plugins )

**Comment by justlevine** [comment] 2022-04-08 03:55
>Still got the issue with no spaces in Custom Post Type names

This is in accordance with the [GraphQL spec](https://spec.graphql.org/June2018/#sec-Names)

**Comment by sirjeff** [comment] 2022-04-08 03:56
> > Still got the issue with no spaces in Custom Post Type names
> 
> This is in accordance with the [GraphQL spec](https://spec.graphql.org/June2018/#sec-Names)

Yup all good I understand. Just testing :)

**Comment by jasonbahl** [comment] 2022-04-20 15:46
@stephenwongcandr have you tried v1.8.1 yet? Can you confirm that the GraphiQL IDE is working again in v1.8.1? Or are you still having issues?

If it's not loading properly, can you inspect the "network" tab of your browser's dev tools and take a look at the request to the `?graphql` endpoint and share what you see?

Here's a video showing how to inspect the request in Chrome's dev tools: https://cln.sh/4Ui7md

**Comment by imjlk** [comment] 2022-04-25 08:16
I'm not sure it's related, 
In my case I'm using just WPGraphQL plugin(version 1.8.0), If my wp site locale setting is Korean(Non-english) below error occurs in browser
```
load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.9.3:5 JQMIGRATE: Migrate is installed, version 3.3.2
app.js?ver=ed1b92d35860129a50b81d00174fd747:38 Uncaught (in promise) GraphQLError: Names must only contain [_a-zA-Z0-9] but "Template_빈 템플릿" does not.
    at a (app.js?ver=ed1b92d35860129a50b81d00174fd747:38:491918)
    at new U (app.js?ver=ed1b92d35860129a50b81d00174fd747:38:498283)
    at app.js?ver=ed1b92d35860129a50b81d00174fd747:38:555696
    at app.js?ver=ed1b92d35860129a50b81d00174fd747:38:557001
    at t.keyValMap (app.js?ver=ed1b92d35860129a50b81d00174fd747:38:441875)
    at t.buildClientSchema (app.js?ver=ed1b92d35860129a50b81d00174fd747:38:555440)
    at app.js?ver=ed1b92d35860129a50b81d00174fd747:38:47
a @ app.js?ver=ed1b92d35860129a50b81d00174fd747:38
U @ app.js?ver=ed1b92d35860129a50b81d00174fd747:38
(anonymous) @ app.js?ver=ed1b92d35860129a50b81d00174fd747:38
(anonymous) @ app.js?ver=ed1b92d35860129a50b81d00174fd747:38
t.keyValMap @ app.js?ver=ed1b92d35860129a50b81d00174fd747:38
t.buildClientSchema @ app.js?ver=ed1b92d35860129a50b81d00174fd747:38
(anonymous) @ app.js?ver=ed1b92d35860129a50b81d00174fd747:38
Promise.then (async)
(anonymous) @ app.js?ver=ed1b92d35860129a50b81d00174fd747:38
Tj @ react-dom.min.js?ver=17.0.1:179
unstable_runWithPriority @ react.min.js?ver=17.0.1:24
Za @ react-dom.min.js?ver=17.0.1:73
Ra @ react-dom.min.js?ver=17.0.1:178
(anonymous) @ react-dom.min.js?ver=17.0.1:178
R @ react.min.js?ver=17.0.1:16
ua.port1.onmessage @ react.min.js?ver=17.0.1:22
```
> `빈 템플릿` is blank template or empty template.

When i change my site locale setting to English, It works.

It maybe occur with translated text.

**Comment by justlevine** [comment] 2022-04-25 08:30
@imjlk that's unrelated. GraphQL names are only alphanumeric, and can't parse Unicode (in this case Korean). I'm not entirely sure how translations work in WP, but my guess is that there should be a way for it to use the English strings when defining default types.

Please open up a new issue (and in the interim you can do a workaround by using the `graphql_type_name` filter to provide transliterated names).

**Comment by jasonbahl** [comment] 2022-05-02 21:00
I believe the original issue has been resolved. I'm going to close this. @imjlk as @justlevine suggested, it would be best to create a new issue with what you're experiencing, and ideally steps to reproduce so we can get into the same situation and experience the same bug.

**Closed by jasonbahl** 2022-05-02 21:00 UTC
Labels: Bug, status: awaiting author response, Regression, GraphiQL, ACF
